=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/CharacterSpecialAdvantages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="MiscTypes.xsd"/>
    <xs:simpleType name="CharacterSpecialAdvantage">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    <xs:simpleType name="CharacterSpecialAdvantageEffect">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    <xs:complexType name="CharacterSpecialAdvantageData">
        <xs:sequence>
            <xs:element name="Name" type="CharacterSpecialAdvantage"/>
            <xs:element name="Effect" type="CharacterSpecialAdvantageEffect"/>
            <xs:element name="Description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="CharacterSpecialAdvantages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CharacterSpecialAdvantage" type="CharacterSpecialAdvantageData" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/CharacterSpecialAdvantages.xml
<?xml version="1.0" encoding="utf-8"?>
<CharacterSpecialAdvantages
      xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    
      xsi:noNamespaceSchemaLocation="CharacterSpecialAdvantages.xsd"> 

    <CharacterSpecialAdvantage>
        <Name>Aim</Name>
        <Effect>Table.Missile.Modifier.DieRolls.-1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Stamina</Name>
        <Effect>Phase.Bonus.Move.+1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Robust</Name>
        <Effect>Phase.Bonus.Rest.+1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Berserk</Name>
        <Effect>Special.Berserk</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Fear</Name>
        <Effect>Table.Meeting.Modifier.Dice.-1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Reputation</Name>
        <Effect>Phase.Bonus.Any.+1[LocationType=Dwelling]</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Concealment</Name>
        <Effect>Table.Hide.Modifier.Dice.-1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Peace with Nature</Name>
        <Effect>Spell.PeaceWithNature</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Short Legs</Name>
        <Effect>Special.ShortLegs</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Cave Knowledge</Name>
        <Effect>Table.Hide|Meeting|Search.Modifier.Dice.-1[LocationType=Cave]</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Elusiveness</Name>
        <Effect>Phase.Bonus.Hide.+1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Archer</Name>
        <Effect>Table.Missile.Modifier.Dice.-1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Magical Paraphernalia</Name>
        <Effect>Phase.Bonus.Alert.+1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Knowledge</Name>
        <Effect>Table.ReadingRunes.Modifier.DieRolls.-1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Heavenly Protection</Name>
        <Effect>Special.HeavenlyProtection</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Learning</Name>
        <Effect>Table.ReadingRunes.Modifier.Dice.-1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Lore</Name>
        <Effect>Table.ReadingRunes.Modifier.Dice.-1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Aura of Power</Name>
        <Effect>Phase.Bonus.Enchant.+1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Barter</Name>
        <Effect>Table.Meeting.Modifier.Dice.-1[PhaseType=Trade]</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Clever</Name>
        <Effect>Spell.Premonition</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Health</Name>
        <Effect>Phase.Bonus.Rest.+1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Honor</Name>
        <Effect>Table.Meeting.Modifier.DieRolls.-1</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Familiar</Name>
        <Effect>Special.Familiar</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Disembodied</Name>
        <Effect>Special.Disembodied</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Experience</Name>
        <Effect>Special.Experience</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
    <CharacterSpecialAdvantage>
        <Name>Tracking Skills</Name>
        <Effect>Table.Hide|Meeting|Search.Modifier.Dice.-1[TileType=Woods]</Effect>
        <Description></Description>
    </CharacterSpecialAdvantage>
</CharacterSpecialAdvantages>
