=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/CharacterClasses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="Armor.xsd"/>
    <xs:include schemaLocation="CharacterSpecialAdvantages.xsd"/>
    <xs:include schemaLocation="Spells.xsd"/>
    <xs:include schemaLocation="Weapons.xsd"/>
    <xs:simpleType name="ChararacterClassLevel">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    <xs:complexType name="CharacterChit">
        <xs:simpleContent>
            <xs:extension base="xs:token">
                <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
                <xs:attribute name="type" type="ChitType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <!-- todo: rename this; used in PC.xsd -->
    <xs:group name="StartingEquipment">
        <xs:choice>
            <xs:element name="Armor" type="Armor"/>
            <xs:element name="Weapon" type="Weapon"/>
            <xs:element name="Spell" type="Spell"/>
        </xs:choice>
    </xs:group>
    <xs:complexType name="ClassLevel">
        <xs:sequence>
            <xs:element name="name" type="ChararacterClassLevel"/>
            <xs:group ref="StartingEquipment" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="CharacterChit" type="CharacterChit" minOccurs="3" maxOccurs="3"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ClassLevels">
        <xs:sequence>
            <xs:element name="ClassLevel" type="ClassLevel" minOccurs="4" maxOccurs="4"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="StartingLocations">
        <xs:sequence>
            <xs:element name="StartingLocation" type="Dwelling" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TradingRelationStatus">
        <xs:restriction base="xs:token">
            <xs:enumeration value="ally"/>
            <xs:enumeration value="friendly"/>
            <xs:enumeration value="neutral"/>
            <xs:enumeration value="unfriendly"/>
            <xs:enumeration value="enemy"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TradingRelation">
        <xs:simpleContent>
            <xs:extension base="VisitorsAndNativeGroups">
                <xs:attribute name="status" type="TradingRelationStatus" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TradingRelations">
        <xs:sequence>
            <xs:element name="TradingRelation" type="TradingRelation" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SpecialAdvantages">
        <xs:sequence>
            <xs:element name="SpecialAdvantage" type="CharacterSpecialAdvantage" minOccurs="2" maxOccurs="2"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CharacterClassData">
        <xs:sequence>
            <xs:element name="Name" type="CharacterClass"/>
            <xs:element name="Weight" type="Weight"/>
            <xs:element name="Symbol" type="NonEmptyString"/>
            <xs:element name="Description" type="xs:string"/>
            <xs:element name="SpecialAdvantages" type="SpecialAdvantages"/>
            <xs:element name="StartingLocations" type="StartingLocations"/>
            <xs:element name="TradingRelations" type="TradingRelations"/>
            <xs:element name="ClassLevels" type="ClassLevels"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="CharacterClasses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CharacterClassData" type="CharacterClassData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/CharacterClasses.xml
<?xml version="1.0" encoding="utf-8"?>
<CharacterClasses xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CharacterClasses.xsd">
    <CharacterClassData>
        <Name>Amazon</Name>
        <Weight>M</Weight>
        <Symbol>Sword and Shield</Symbol>
        <Description>Amazon</Description>
        <SpecialAdvantages>
            <SpecialAdvantage>Aim</SpecialAdvantage>
            <SpecialAdvantage>Stamina</SpecialAdvantage>
        </SpecialAdvantages>
        <StartingLocations>
            <StartingLocation>Inn</StartingLocation>
        </StartingLocations>
        <TradingRelations>
            <TradingRelation status="friendly">Lancers</TradingRelation>
            <TradingRelation status="friendly">Patrol</TradingRelation>
            <TradingRelation status="friendly">Shaman</TradingRelation>
            <TradingRelation status="unfriendly">Company</TradingRelation>
            <TradingRelation status="unfriendly">Bashkars</TradingRelation>
        </TradingRelations>
        <ClassLevels>
            <ClassLevel>
                <name>Scout</name>
                <Weapon>Light Bow</Weapon>
                <CharacterChit id="1" type="move">M4</CharacterChit>
                <CharacterChit id="2" type="move">M3*</CharacterChit>
                <CharacterChit id="3" type="fight">L4</CharacterChit>
            </ClassLevel>
            <ClassLevel>
                <name>Warrior</name>
                <Weapon>Spear</Weapon>
                <Armor>Helmet</Armor>
                <Armor>Breastplate</Armor>
                <Armor>Shield</Armor>
                <CharacterChit id="4" type="move">M4</CharacterChit>
                <CharacterChit id="5" type="fight">M5</CharacterChit>
                <CharacterChit id="6" type="fight">M4*</CharacterChit>
            </ClassLevel>
            <ClassLevel>
                <name>Champion</name>
                <Weapon>Spear</Weapon>
                <Armor>Helmet</Armor>
                <Armor>Breastplate</Armor>
                <Armor>Shield</Armor>
                <CharacterChit id="7" type="move">M3*</CharacterChit>
                <CharacterChit id="8" type="fight">M3**</CharacterChit>
                <CharacterChit id="9" type="fight">H4**</CharacterChit>
            </ClassLevel>
            <ClassLevel>
                <name>Amazon</name>
                <Weapon>Short Sword</Weapon>
                <Armor>Helmet</Armor>
                <Armor>Breastplate</Armor>
                <Armor>Shield</Armor>
                <CharacterChit id="10" type="fight">M4*</CharacterChit>
                <CharacterChit id="11" type="fight">M3**</CharacterChit>
                <CharacterChit id="12" type="move">M3*</CharacterChit>
            </ClassLevel>
        </ClassLevels>
    </CharacterClassData>
</CharacterClasses>
        
    
    <!--
                <StartingEquipmentList>
                </StartingEquipmentList>
        <Equipment>
            <Weapon>Short Sword</Weapon>
            <Armor>Helmet</Armor>
            <Armor>Breastplate</Armor>
            <Armor>Shield</Armor>
        </Equipment>

    <CharacterClass name="Dwarf" weight="H">
        <Symbol>Opposition</Symbol>

        <StartingLocations>
            <StartingLocation>Inn</StartingLocation>
            <StartingLocation>Guardhouse</StartingLocation>
        </StartingLocations>

        <TradingRelations>
            <TradingRelation status="friendly">Company</TradingRelation>
            <TradingRelation status="friendly">Guard</TradingRelation>
            <TradingRelation status="friendly">Scholar</TradingRelation>
            <TradingRelation status="unfriendly">Woodfolk</TradingRelation>
            <TradingRelation status="unfriendly">Bashkars</TradingRelation>
        </TradingRelations>
        <SpecialAdvantages>
            <SpecialAdvantage>Short Legs</SpecialAdvantage>
            <SpecialAdvantage>Cave Knowledge</SpecialAdvantage>
        </SpecialAdvantages>
        
        <Chits>
            <Chit type="Duck">T3*</Chit>
            <Chit type="Move">H6</Chit>
            <Chit type="Fight">H5*</Chit>
            <Chit type="Move">T6*</Chit>
            <Chit type="Fight">H6</Chit>
            <Chit type="Fight">H4**</Chit>
            <Chit type="Move">H5*</Chit>
            <Chit type="Fight">T6*</Chit>
            <Chit type="Fight">H4**</Chit>
            <Chit type="Fight">T5**</Chit>
            <Chit type="Fight">T5**</Chit>
            <Chit type="Move">T5**</Chit>
        </Chits>

        <Equipment>
            <Weapon>Great Axe</Weapon>
            <Armor>Helmet</Armor>
        </Equipment>

    </CharacterClass>

    <CharacterClass name="Swordsman" weight="L">
        <Symbol>Wolf's Hook</Symbol>

        <StartingLocations>
            <StartingLocation>Inn</StartingLocation>
        </StartingLocations>

        <TradingRelations>
            <TradingRelation status="friendly">Rogues</TradingRelation>
            <TradingRelation status="friendly">Company</TradingRelation>
            <TradingRelation status="friendly">Warlock</TradingRelation>
            <TradingRelation status="Enemy">Patrol</TradingRelation>
        </TradingRelations>

        <SpecialAdvantages>
            <SpecialAdvantage>Barter</SpecialAdvantage>
            <SpecialAdvantage>Clever</SpecialAdvantage>
        </SpecialAdvantages>
        
        <Chits>
            <Chit type="Move">L4</Chit>
            <Chit type="Move">L3*</Chit>
            <Chit type="Fight">L3*</Chit>
            <Chit type="Move">L3*</Chit>
            <Chit type="Fight">L2**</Chit>
            <Chit type="Move">L2**</Chit>
            <Chit type="Move">M4*</Chit>
            <Chit type="Fight">M4*</Chit>
            <Chit type="Fight">M3**</Chit>
            <Chit type="Fight">L4</Chit>
            <Chit type="Fight">M5</Chit>
            <Chit type="Fight">L2**</Chit>
        </Chits>

        <Equipment>
            <Weapon>Thrusting Sword</Weapon>
        </Equipment>

    </CharacterClass>

    <CharacterClass name="White Knight" weight="H">
        <Symbol>"Cross Pommee": Potent Cross</Symbol>

        <StartingLocations>
            <StartingLocation>Inn</StartingLocation>
            <StartingLocation>Chapel</StartingLocation>
        </StartingLocations>

        <TradingRelations>
            <TradingRelation status="Ally">Order</TradingRelation>
            <TradingRelation status="friendly">Lancers</TradingRelation>
            <TradingRelation status="unfriendly">Bashkars</TradingRelation>
            <TradingRelation status="unfriendly">Crone</TradingRelation>
            <TradingRelation status="Enemy">Company</TradingRelation>
        </TradingRelations>

        <SpecialAdvantages>
            <SpecialAdvantage>Health</SpecialAdvantage>
            <SpecialAdvantage>Honor</SpecialAdvantage>
        </SpecialAdvantages>
        
        <Chits>
            <Chit type="Fight">H5*</Chit>
            <Chit type="Fight">H6</Chit>
            <Chit type="Fight">H5*</Chit>
            <Chit type="Fight">H4**</Chit>
            <Chit type="Fight">H6</Chit>
            <Chit type="Fight">H4**</Chit>
            <Chit type="Fight">H4**</Chit>
            <Chit type="Fight">H5*</Chit>
            <Chit type="Magic">I5**</Chit>
            <Chit type="Move">T6*</Chit>
            <Chit type="Fight">T4**</Chit>
            <Chit type="Fight">T5*</Chit>
        </Chits>

        <Equipment>
            <Weapon>Greatsword</Weapon>
            <Armor>Armor</Armor>
            <Spell type="I"></Spell>
        </Equipment>
    </CharacterClass>
-->
