=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/MagicTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="MiscTypes.xsd"/>
    <xs:simpleType name="RitualMagic">
        <xs:restriction base="NonEmptyToken"/>
    </xs:simpleType>
    <xs:simpleType name="ColorMagic">
        <xs:restriction base="NonEmptyToken"/>
    </xs:simpleType>
    <xs:simpleType name="ColorMagicList">
        <xs:list itemType="ColorMagic"/>
    </xs:simpleType>
    
    <xs:simpleType name="Spell">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    <xs:complexType name="MagicTypeData">
        <xs:sequence>
            <xs:element name="Type" type="RitualMagic"/>
            <xs:element name="Color" type="ColorMagic" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <!-- assume a pc -->
    <xs:simpleType name="CasterId">
        <xs:restriction base="CharacterName"/>
    </xs:simpleType>
    <!-- pc, native, tile, clearing, spell, etc -->
    <xs:simpleType name="SpellTarget">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    <!-- todo: day, round -->
    <xs:complexType name="SpellStartTime">
        <xs:sequence>
            <xs:element name="Day" type="GameDays"/>
            <xs:element name="Round" type="GameRounds"/>
        </xs:sequence>
    </xs:complexType>
    <!-- todo: -->
    <xs:simpleType name="SpellDuration">
        <xs:restriction base="NonEmptyToken"/>
    </xs:simpleType>
    <xs:complexType name="SpellTargets">
        <xs:sequence>
            <xs:element name="Target" type="SpellTarget" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- todo: source = chit-id, tile, treasure, etc -->
    <xs:complexType name="SpellColorMagicSource">
        <xs:sequence>
            <xs:element name="Color" type="ColorMagic"/>
            <xs:element name="source" type="NonEmptyString"/>
        </xs:sequence>
    </xs:complexType>
    <!-- for permanent spells -->
    <xs:complexType name="SpellActivationStatus">
        <xs:sequence>
            <xs:element name="Activated" type="xs:boolean"/>
            <xs:element name="ColorSource" type="SpellColorMagicSource"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="BewitchmentId">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    <xs:complexType name="Bewitchment">
        <xs:sequence>
            <xs:element name="ID" type="BewitchmentId"/>
            <xs:element name="Spell" type="Spell"/>
            <xs:element name="Caster" type="CasterId"/>
            <xs:element name="Targets" type="SpellTargets"/>
            <xs:element name="StartTime" type="SpellStartTime"/>
            <xs:element name="Duration" type="SpellDuration"/>
            <xs:element name="Activated" type="SpellActivationStatus" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Bewitchments">
        <xs:sequence>
            <xs:element name="Bewitchment" type="Bewitchment" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="CurseType">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    <xs:complexType name="CurseData">
        <xs:sequence>
            <xs:element name="Name" type="CurseType"/>
            <xs:element name="Description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Curse">
        <xs:sequence>
            <xs:element name="Curse" type="CurseType"/>
            <xs:element name="DayAfflicted" type="GameDays"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Curses">
        <xs:sequence>
            <xs:element name="Curse" type="Curse" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="MagicTypeDataList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MagicTypeData" type="MagicTypeData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/MagicTypes.xml
<?xml version="1.0" encoding="utf-8"?>
<MagicTypeDataList
      xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    
      xsi:noNamespaceSchemaLocation="MagicTypes.xsd">

    <!-- todo: add Ritual Descriptions (eg: Righteous Invocations) and color-magic descriptions (eg: Power from on High etc) -->
    <MagicTypeData>
        <Type>I</Type>
        <Color>White</Color>
    </MagicTypeData>
    <MagicTypeData>
        <Type>II</Type>
        <Color>Grey</Color>
    </MagicTypeData>
    <MagicTypeData>
        <Type>III</Type>
        <Color>Gold</Color>
    </MagicTypeData>
    <MagicTypeData>
        <Type>IV</Type>
        <Color>Purple</Color>
    </MagicTypeData>
    <MagicTypeData>
        <Type>V</Type>
        <Color>Black</Color>
    </MagicTypeData>
    <MagicTypeData>
        <Type>VI</Type>
    </MagicTypeData>
    <MagicTypeData>
        <Type>VII</Type>
    </MagicTypeData>
    <MagicTypeData>
        <Type>VIII</Type>
    </MagicTypeData>
</MagicTypeDataList>
