=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/Missions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="MiscTypes.xsd"/>
    <xs:complexType name="MissionData">
        <xs:sequence>
            <xs:element name="Name" type="Mission"/>
            <xs:element name="NotorietyCost" type="NotorietyType"/>
            <xs:element name="GoldRewardPerClearing" type="GoldPrice"/>
            <xs:element name="PrimaryDestination" type="Dwelling"/>
            <xs:element name="SecondaryDestination" type="Dwelling"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="MissionDataList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mission" type="MissionData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/Missions.xml
<?xml version="1.0" encoding="utf-8"?>
<MissionDataList
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"                   
        xsi:noNamespaceSchemaLocation="Missions.xsd">
  <Mission>
    <Name>Escort Party</Name>
    <NotorietyCost>5</NotorietyCost>
    <GoldRewardPerClearing>2</GoldRewardPerClearing>
    <PrimaryDestination>Inn</PrimaryDestination>
    <SecondaryDestination>House</SecondaryDestination>
  </Mission>

  <Mission>
    <Name>Food/Ale</Name>
    <NotorietyCost>5</NotorietyCost>
    <GoldRewardPerClearing>2</GoldRewardPerClearing>
    <PrimaryDestination>Chapel</PrimaryDestination>
    <SecondaryDestination>Guardhouse</SecondaryDestination>
  </Mission>
</MissionDataList>
