=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/Monsters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="MiscTypes.xsd"/>
    <xs:include schemaLocation="Weapons.xsd"/>
    <!-- todo: union of weapon, striking (tooth/claw), spell, etc 
        FK?
    -->
    <!-- todo: firebreathing optional -->
    <xs:simpleType name="MonsterAttackType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Melee"/>
            <xs:enumeration value="Head"/>
            <xs:enumeration value="Club"/>
            <xs:enumeration value="Power of the Pit"/>
            <xs:enumeration value="Curse"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="MonsterAttackValue">
        <xs:restriction base="NonEmptyToken"/>
    </xs:simpleType>
    <xs:complexType name="MonsterAttack">
        <xs:sequence>
            <xs:element name="Type" type="MonsterAttackType"/>
            <xs:element name="Length" type="WeaponLength"/>
            <xs:element name="Unalerted" type="MonsterAttackValue"/>
            <xs:element name="Alerted" type="MonsterAttackValue"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MonsterData">
        <xs:sequence>
            <xs:element name="Name" type="Monster"/>
            <xs:element name="Size" type="Weight"/>
            <xs:element name="Armored" type="xs:boolean"/>
            <xs:element name="Attack" type="MonsterAttack"/>
            <xs:element name="SecondaryAttack" type="MonsterAttack" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Fame" type="FameType"/>
            <xs:element name="Notoriety" type="NotorietyType"/>
            <xs:element name="Flies" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="Monsters">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Monster" type="MonsterData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/Monsters.xml
<?xml version="1.0" encoding="utf-8"?>
<Monsters xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Monsters.xsd">
    <Monster>
        <Name>T Flying Dragon</Name>
        <Size>T</Size>
        <Armored>true</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>M34</Unalerted>
            <Alerted>O64</Alerted>
        </Attack>
        <SecondaryAttack>
            <Type>Head</Type>
            <Length>7</Length>
            <Unalerted>M3</Unalerted>
            <Alerted>T3</Alerted>
        </SecondaryAttack>
        <Fame>12</Fame>
        <Notoriety>12</Notoriety>
        <Flies>true</Flies>
    </Monster>
    <Monster>
        <Name>T Dragon</Name>
        <Size>T</Size>
        <Armored>true</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>H56</Unalerted>
            <Alerted>O36</Alerted>
        </Attack>
        <SecondaryAttack>
            <Type>Head</Type>
            <Length>9</Length>
            <Unalerted>H4</Unalerted>
            <Alerted>T4</Alerted>
        </SecondaryAttack>
        <Fame>10</Fame>
        <Notoriety>10</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Giant</Name>
        <Size>T</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>H55</Unalerted>
            <Alerted>O46</Alerted>
        </Attack>
        <SecondaryAttack>
            <Type>Club</Type>
            <Length>9</Length>
            <Unalerted>H6</Unalerted>
            <Alerted>T4</Alerted>
        </SecondaryAttack>
        <Fame>8</Fame>
        <Notoriety>8</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Winged Demon</Name>
        <Size>T</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Power of the Pit</Type>
            <Length>17</Length>
            <Unalerted>V33</Unalerted>
            <Alerted>O52</Alerted>
        </Attack>
        <Fame>8</Fame>
        <Notoriety>8</Notoriety>
        <Flies>true</Flies>
    </Monster>
    <Monster>
        <Name>Demon</Name>
        <Size>T</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Power of the Pit</Type>
            <Length>17</Length>
            <Unalerted>V24</Unalerted>
            <Alerted>O44</Alerted>
        </Attack>
        <Fame>8</Fame>
        <Notoriety>8</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>T Troll</Name>
        <Size>T</Size>
        <Armored>true</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>H44</Unalerted>
            <Alerted>O26</Alerted>
        </Attack>
        <Fame>8</Fame>
        <Notoriety>8</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Octopus</Name>
        <Size>T</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>L42</Unalerted>
            <Alerted>O43</Alerted>
        </Attack>
        <Fame>8</Fame>
        <Notoriety>8</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <!-- Tables have a typo and do not show T Serpent as armored. All serpents are armored (19.2/2 2nd ed). -->
    <Monster>
        <Name>T Serpent</Name>
        <Size>T</Size>
        <Armored>true</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>M43</Unalerted>
            <Alerted>O45</Alerted>
        </Attack>
        <Fame>7</Fame>
        <Notoriety>7</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>T Spider</Name>
        <Size>T</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>M43</Unalerted>
            <Alerted>O54</Alerted>
        </Attack>
        <Fame>6</Fame>
        <Notoriety>6</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>H Flying Dragon</Name>
        <Size>H</Size>
        <Armored>true</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>H44</Unalerted>
            <Alerted>L43</Alerted>
        </Attack>
        <Fame>5</Fame>
        <Notoriety>5</Notoriety>
        <Flies>true</Flies>
    </Monster>
    <Monster>
        <Name>H Dragon</Name>
        <Size>H</Size>
        <Armored>true</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>H44</Unalerted>
            <Alerted>M43</Alerted>
        </Attack>
        <Fame>5</Fame>
        <Notoriety>5</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>H Troll</Name>
        <Size>H</Size>
        <Armored>true</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>M44</Unalerted>
            <Alerted>H54</Alerted>
        </Attack>
        <Fame>5</Fame>
        <Notoriety>5</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>H Serpent</Name>
        <Size>H</Size>
        <Armored>true</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>L44</Unalerted>
            <Alerted>H54</Alerted>
        </Attack>
        <Fame>4</Fame>
        <Notoriety>4</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Giant Bat</Name>
        <Size>H</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>M23</Unalerted>
            <Alerted>M32</Alerted>
        </Attack>
        <Fame>3</Fame>
        <Notoriety>3</Notoriety>
        <Flies>true</Flies>
    </Monster>
    <Monster>
        <Name>H Spider</Name>
        <Size>H</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>L43</Unalerted>
            <Alerted>T64</Alerted>
        </Attack>
        <Fame>3</Fame>
        <Notoriety>3</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Imp</Name>
        <Size>M</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Curse</Type>
            <Length>17</Length>
            <Unalerted>VIII22</Unalerted>
            <Alerted>M43</Alerted>
        </Attack>
        <Fame>2</Fame>
        <Notoriety>1</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Goblin with Spear</Name>
        <Size>M</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>10</Length>
            <Unalerted>-3</Unalerted>
            <Alerted>H5*5</Alerted>
        </Attack>
        <Fame>1</Fame>
        <Notoriety>1</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Goblin with Great Sword</Name>
        <Size>M</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>8</Length>
            <Unalerted>H6*3</Unalerted>
            <Alerted>T5*5</Alerted>
        </Attack>
        <Fame>1</Fame>
        <Notoriety>1</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Goblin with Axe</Name>
        <Size>M</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>2</Length>
            <Unalerted>L4*3</Unalerted>
            <Alerted>M4*4</Alerted>
        </Attack>
        <Fame>1</Fame>
        <Notoriety>1</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Viper</Name>
        <Size>M</Size>
        <Armored>true</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>M4**4</Unalerted>
            <Alerted>L22</Alerted>
        </Attack>
        <Fame>1</Fame>
        <Notoriety>2</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Ghost</Name>
        <Size>M</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>H44</Unalerted>
            <Alerted>L22</Alerted>
        </Attack>
        <Fame>0</Fame>
        <Notoriety>2</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Ogre</Name>
        <Size>M</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>T55</Unalerted>
            <Alerted>H54</Alerted>
        </Attack>
        <Fame>0</Fame>
        <Notoriety>2</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Wolf1</Name>
        <Size>M</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
            <Unalerted>L43</Unalerted>
            <Alerted>M44</Alerted>
        </Attack>
        <Fame>0</Fame>
        <Notoriety>1</Notoriety>
        <Flies>false</Flies>
    </Monster>
    <Monster>
        <Name>Wolf2</Name>
        <Size>M</Size>
        <Armored>false</Armored>
        <Attack>
            <Type>Melee</Type>
            <Length>0</Length>
