=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/MonsterGroups.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="Monsters.xsd"/>
    <xs:complexType name="MonsterGroupData">
        <xs:sequence>
            <xs:element name="Name" type="MonsterGroup"/>
            <xs:element name="Member" type="Monster" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="MonsterGroups">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MonsterGroupData" type="MonsterGroupData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/MonsterGroups.xml
<?xml version="1.0" encoding="utf-8"?>
<MonsterGroups xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MonsterGroups.xsd">
    <MonsterGroupData>
        <Name>Dragons</Name>
        <Member>T Flying Dragon</Member>
        <Member>T Dragon</Member>
        <Member>H Flying Dragon</Member>
        <Member>H Dragon</Member>
    </MonsterGroupData>
    <MonsterGroupData>
        <!-- does not include imp -->
        <Name>Demons</Name>
        <Member>Demon</Member>
        <Member>Winged Dragon</Member>
    </MonsterGroupData>
    <MonsterGroupData>
        <Name>Goblins</Name>
        <Member>Goblin with Spear</Member>
        <Member>Goblin with Great Sword</Member>
        <Member>Goblin with Axe</Member>
    </MonsterGroupData>
    <MonsterGroupData>
        <Name>Wolves</Name>
        <Member>Wolf1</Member>
        <Member>Wolf2</Member>
    </MonsterGroupData>
    <MonsterGroupData>
        <Name>Trolls</Name>
        <Member>T Troll</Member>
        <Member>H Troll</Member>
    </MonsterGroupData>
    <MonsterGroupData>
        <Name>Spiders</Name>
        <Member>T Spider</Member>
        <Member>H Spider</Member>
    </MonsterGroupData>
    <MonsterGroupData>
        <Name>Serpents</Name>
        <Member>T Serpent</Member>
        <Member>H Serpent</Member>
    </MonsterGroupData>
    <MonsterGroupData>
        <Name>Bats</Name>
        <Member>Giant Bat</Member>
    </MonsterGroupData>
    <MonsterGroupData>
        <Name>Giants</Name>
        <Member>Giant</Member>
    </MonsterGroupData>
    <MonsterGroupData>
        <Name>Ogres</Name>
        <Member>Ogre</Member>
    </MonsterGroupData>
</MonsterGroups>
