=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/Tiles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="MiscTypes.xsd"/>
    <xs:include schemaLocation="MagicTypes.xsd"/>
    <xs:simpleType name="TileId">
        <xs:restriction base="NonEmptyToken"/>
    </xs:simpleType>
    <xs:simpleType name="TileType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="V"/>
            <xs:enumeration value="M"/>
            <xs:enumeration value="C"/>
            <xs:enumeration value="W"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ClearingType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="M"/>
            <xs:enumeration value="C"/>
            <xs:enumeration value="W"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TileName">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    <xs:simpleType name="Path">
        <xs:restriction base="NonEmptyToken"/>
    </xs:simpleType>
    <xs:simpleType name="PathType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="Road"/>
            <xs:enumeration value="Tunnel"/>
            <xs:enumeration value="Hidden"/>
            <xs:enumeration value="Secret"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="MapEdge">
        <xs:restriction base="xs:token">
            <xs:enumeration value="N"/>
            <xs:enumeration value="NE"/>
            <xs:enumeration value="SE"/>
            <xs:enumeration value="S"/>
            <xs:enumeration value="SW"/>
            <xs:enumeration value="NW"/>
        </xs:restriction>
    </xs:simpleType>
    <!--    
    <xs:element name="PathNode" type="NonEmptyToken" abstract="true"/>
    <xs:element name="PathClearing" substitutionGroup="PathNode">
        <xs:simpleType>
            <xs:restriction base="Clearing"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="MapEdge" type="MapEdge" substitutionGroup="PathNode"/>
-->
    <xs:simpleType name="PathNode">
        <xs:union memberTypes="MapEdge Clearing"/>
    </xs:simpleType>
    <xs:complexType name="ClearingData">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="number" type="Clearing" use="required"/>
                <xs:attribute name="type" type="ClearingType" use="required"/>
                <xs:attribute name="color_magic" type="ColorMagicList" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="ClearingDataList">
        <xs:sequence>
            <xs:element name="Clearing" type="ClearingData" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PathData">
        <xs:attribute name="type" type="PathType" use="required"/>
        <xs:attribute name="node1" type="PathNode" use="required"/>
        <xs:attribute name="node2" type="PathNode" use="required"/>
    </xs:complexType>
    <xs:complexType name="PathDataList">
        <xs:sequence>
            <xs:element name="Path" type="PathData" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TileSide">
        <xs:sequence>
            <xs:element name="Clearings" type="ClearingDataList" maxOccurs="unbounded"/>
            <xs:element name="Paths" type="PathDataList" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TileData">
        <xs:sequence>
            <xs:element name="NormalSide" type="TileSide"/>
            <xs:element name="EnchantedSide" type="TileSide"/>
        </xs:sequence>
        <xs:attribute name="name" type="TileName" use="required"/>
        <xs:attribute name="id" type="TileId" use="required"/>
        <xs:attribute name="type" type="TileType" use="required"/>
    </xs:complexType>
    <xs:element name="TileDataList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Tile" type="TileData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/Tiles.xml
<?xml version="1.0" encoding="utf-8"?>
<TileDataList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Tiles.xsd">
    <Tile name="Awful Valley" id="AV" type="V">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="W"/>
                <Clearing number="2" type="W"/>
                <Clearing number="4" type="W"/>
                <Clearing number="5" type="W"/>
            </Clearings>
            <Paths>
                <Path type="Road" node1="1" node2="NW"/>
                <Path type="Road" node1="1" node2="4"/>
                <Path type="Road" node1="2" node2="SW"/>
                <Path type="Road" node1="2" node2="5"/>
                <Path type="Road" node1="4" node2="NE"/>
                <Path type="Road" node1="4" node2="SE"/>
                <Path type="Road" node1="1" node2="N"/>
            </Paths>
        </NormalSide>
    </Tile>
    <Tile name="Bad Valley" id="BV" type="V">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="W"/>
                <Clearing number="2" type="W"/>
                <Clearing number="4" type="W"/>
                <Clearing number="5" type="W"/>
            </Clearings>
            <Paths>
                <Path type="Road" node1="1" node2="4"/>
                <Path type="Road" node1="1" node2="SE"/>
                <Path type="Road" node1="2" node2="SW"/>
                <Path type="Road" node1="2" node2="5"/>
                <Path type="Road" node1="4" node2="NW"/>
                <Path type="Road" node1="4" node2="N"/>
                <Path type="Road" node1="5" node2="NE"/>
            </Paths>
        </NormalSide>
    </Tile>
    <Tile name="Border Land" id="BL" type="C">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="W"/>
                <Clearing number="2" type="W"/>
                <Clearing number="3" type="W"/>
                <Clearing number="4" type="C"/>
                <Clearing number="5" type="C"/>
                <Clearing number="6" type="C"/>
            </Clearings>
            <Paths>
                <Path type="Road" node1="1" node2="SW"/>
                <Path type="Road" node1="1" node2="N"/>
                <Path type="Road" node1="1" node2="6"/>
                <Path type="Road" node1="2" node2="NE"/>
                <Path type="Road" node1="2" node2="S"/>
                <Path type="Road" node1="2" node2="3"/>
                <Path type="Road" node1="3" node2="5"/>
                <Path type="Road" node1="3" node2="6"/>
                <Path type="Tunnel" node1="4" node2="SE"/>
                <Path type="Secret" node1="4" node2="5"/>
                <Path type="Tunnel" node1="4" node2="6"/>
                <Path type="Tunnel" node1="5" node2="NW"/>
            </Paths>
        </NormalSide>
    </Tile>
    <Tile name="Cavern" id="CA" type="C">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="C"/>
                <Clearing number="2" type="C"/>
                <Clearing number="3" type="C"/>
                <Clearing number="4" type="C"/>
                <Clearing number="5" type="C"/>
                <Clearing number="6" type="C"/>
            </Clearings>
            <Paths>
                <Path type="Road" node1="1" node2="NE"/>
                <Path type="Tunnel" node1="1" node2="3"/>
                <Path type="Secret" node1="1" node2="4"/>
                <Path type="Road" node1="2" node2="N"/>
                <Path type="Tunnel" node1="2" node2="3"/>
                <Path type="Secret" node1="3" node2="5"/>
                <Path type="Tunnel" node1="3" node2="6"/>
                <Path type="Tunnel" node1="4" node2="5"/>
                <Path type="Tunnel" node1="4" node2="6"/>
                <Path type="Road" node1="5" node2="NW"/>
            </Paths>
        </NormalSide>
    </Tile>
    <Tile name="Caves" id="CS" type="C">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="C"/>
                <Clearing number="2" type="C"/>
                <Clearing number="3" type="C"/>
                <Clearing number="4" type="C"/>
                <Clearing number="5" type="C"/>
                <Clearing number="6" type="C"/>
            </Clearings>
            <Paths>
                <Path type="Road" node1="1" node2="SE"/>
                <Path type="Tunnel" node1="1" node2="6"/>
                <Path type="Road" node1="2" node2="SW"/>
                <Path type="Secret" node1="2" node2="3"/>
                <Path type="Tunnel" node1="2" node2="4"/>
                <Path type="Tunnel" node1="3" node2="5"/>
                <Path type="Tunnel" node1="4" node2="6"/>
                <Path type="Road" node1="5" node2="NW"/>
            </Paths>
        </NormalSide>
    </Tile>
    <Tile name="Crag" id="CR" type="M">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="M"/>
                <Clearing number="2" type="M"/>
                <Clearing number="3" type="M"/>
                <Clearing number="4" type="M"/>
                <Clearing number="5" type="M"/>
                <Clearing number="6" type="M"/>
            </Clearings>
            <Paths>
                <Path type="Road" node1="1" node2="4"/>
                <Path type="Secret" node1="1" node2="6"/>
                <Path type="Road" node1="2" node2="N"/>
                <Path type="Hidden" node1="2" node2="3"/>
                <Path type="Road" node1="2" node2="5"/>
                <Path type="Road" node1="3" node2="5"/>
                <Path type="Road" node1="3" node2="6"/>
                <Path type="Road" node1="4" node2="6"/>
            </Paths>
        </NormalSide>
    </Tile>
    <Tile name="Cliff" id="CL" type="M">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="M"/>
                <Clearing number="2" type="W"/>
                <Clearing number="3" type="W"/>
                <Clearing number="4" type="M"/>
                <Clearing number="5" type="W"/>
                <Clearing number="6" type="M"/>
            </Clearings>
            <Paths>
                <Path type="Road" node1="1" node2="NW"/>
                <Path type="Road" node1="1" node2="6"/>
                <Path type="Road" node1="2" node2="SW"/>
                <Path type="Road" node1="2" node2="3"/>
                <Path type="Hidden" node1="2" node2="5"/>
                <Path type="Road" node1="3" node2="5"/>
                <Path type="Secret" node1="3" node2="6"/>
                <Path type="Road" node1="4" node2="NE"/>
                <Path type="Road" node1="4" node2="6"/>
                <Path type="Road" node1="5" node2="SE"/>
            </Paths>
        </NormalSide>
    </Tile>
    <Tile name="Curst Valley" id="CV" type="V">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="W"/>
                <Clearing number="2" type="W"/>
                <Clearing number="4" type="W"/>
                <Clearing number="5" type="W"/>
            </Clearings>
            <Paths>
                <Path type="Road" node1="1" node2="N"/>
                <Path type="Road" node1="1" node2="4"/>
                <Path type="Road" node1="2" node2="NW"/>
                <Path type="Road" node1="2" node2="5"/>
                <Path type="Road" node1="4" node2="SW"/>
                <Path type="Road" node1="4" node2="SE"/>
                <Path type="Road" node1="5" node2="NE"/>
            </Paths>
        </NormalSide>
    </Tile>
    <Tile name="Dark Valley" id="DV" type="V">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="W"/>
                <Clearing number="2" type="W"/>
                <Clearing number="4" type="W"/>
                <Clearing number="5" type="W"/>
            </Clearings>
            <Paths>
                <Path type="Road" node1="1" node2="NE"/>
                <Path type="Road" node1="1" node2="4"/>
                <Path type="Road" node1="2" node2="N"/>
                <Path type="Road" node1="2" node2="5"/>
                <Path type="Road" node1="4" node2="SW"/>
                <Path type="Road" node1="4" node2="NW"/>
                <Path type="Road" node1="5" node2="SE"/>
            </Paths>
        </NormalSide>
    </Tile>
    <Tile name="Deep Woods" id="DW" type="M">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="W"/>
                <Clearing number="2" type="W"/>
                <Clearing number="3" type="W"/>
                <Clearing number="4" type="W"/>
                <Clearing number="5" type="W"/>
                <Clearing number="6" type="W"/>
            </Clearings>
            <Paths>
                <Path type="Road" node1="1" node2="NW"/>
                <Path type="Road" node1="1" node2="N"/>
                <Path type="Hidden" node1="1" node2="4"/>
                <Path type="Road" node1="1" node2="6"/>
                <Path type="Road" node1="2" node2="NE"/>
                <Path type="Road" node1="2" node2="SE"/>
                <Path type="Road" node1="2" node2="3"/>
                <Path type="Road" node1="3" node2="5"/>
                <Path type="Hidden" node1="3" node2="6"/>
                <Path type="Road" node1="4" node2="5"/>
                <Path type="Road" node1="4" node2="6"/>
                <Path type="Road" node1="5" node2="SW"/>
            </Paths>
        </NormalSide>
    </Tile>
    <Tile name="Evil Valley" id="EV" type="V">
        <NormalSide>
            <Clearings>
                <Clearing number="1" type="W"/>
