=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/TileCoordinateData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="Tiles.xsd"/>
    <xs:simpleType name="TilePathArc">
        <xs:restriction base="xs:float"/>
    </xs:simpleType>
    <xs:complexType name="OffroadCoordinates">
        <xs:attribute name="x" type="xs:float" use="required"/>
        <xs:attribute name="y" type="xs:float" use="required"/>
    </xs:complexType>
    <xs:complexType name="TileClearingCoordinates">
        <xs:attribute name="clearing" type="Clearing" use="required"/>
        <xs:attribute name="x" type="xs:float" use="required"/>
        <xs:attribute name="y" type="xs:float" use="required"/>
    </xs:complexType>
    <xs:complexType name="TilePathArcElement">
        <xs:attribute name="path" type="xs:integer" use="optional"/>
        <xs:attribute name="from" type="PathNode" use="required"/>
        <xs:attribute name="to" type="PathNode" use="required"/>
        <xs:attribute name="arc1" type="TilePathArc" use="required"/>
        <xs:attribute name="arc2" type="TilePathArc" use="required"/>
    </xs:complexType>
    <xs:complexType name="TileCoordinateSide">
        <xs:sequence>
            <xs:element name="OffroadCoordinates" type="OffroadCoordinates"/>
            <xs:element name="ClearingCoordinates" type="TileClearingCoordinates" maxOccurs="unbounded"/>
            <xs:element name="PathArc" type="TilePathArcElement" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TileCoordinateData">
        <xs:sequence>
            <xs:element name="TileImage" type="xs:string"/>
            <xs:element name="NormalSide" type="TileCoordinateSide"/>
            <xs:element name="EnchantedSide" type="TileCoordinateSide"/>
        </xs:sequence>
        <xs:attribute name="tile" type="TileId" use="required"/>
    </xs:complexType>
    <xs:element name="TileCoordinateDataList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TileCoordinateData" type="TileCoordinateData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/TileCoordinateData.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by foobar (ORiON) -->
<TileCoordinateDataList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TileCoordinateData.xsd">
<!-- some of these are not used; eg: image, PathArc path-attributes, 
-->
  <TileCoordinateData tile="AV">
    <TileImage>awfulvalley</TileImage>
    <NormalSide>
      <OffroadCoordinates x="47.1" y="81.8" />
      <ClearingCoordinates clearing="1" x="25.2" y="34.9" />
      <ClearingCoordinates clearing="2" x="25.4" y="65.9" />
      <ClearingCoordinates clearing="4" x="62.2" y="59.9" />
      <ClearingCoordinates clearing="5" x="48.7" y="20.7" />
      <PathArc path="2" from="2" to="5" arc1="43.1" arc2="44.9" />
      <PathArc path="5" from="4" to="NE" arc1="69.9" arc2="39.8" />
    </NormalSide>
    <EnchantedSide>
      <OffroadCoordinates x="48.5" y="81.8" />
      <ClearingCoordinates clearing="1" x="26.6" y="36.3" />
      <ClearingCoordinates clearing="2" x="26.6" y="65.9" />
      <ClearingCoordinates clearing="4" x="60.8" y="57.5" />
      <ClearingCoordinates clearing="5" x="48.9" y="20.2" />
      <PathArc path="2" from="2" to="5" arc1="44.7" arc2="48.0" />
      <PathArc path="5" from="4" to="NE" arc1="67.3" arc2="40.7" />
    </EnchantedSide>
  </TileCoordinateData>
  <TileCoordinateData tile="BV">
    <TileImage>badvalley</TileImage>
    <NormalSide>
      <OffroadCoordinates x="48.9" y="80.8" />
      <ClearingCoordinates clearing="1" x="75.0" y="65.2" />
      <ClearingCoordinates clearing="2" x="27.6" y="64.8" />
      <ClearingCoordinates clearing="4" x="36.6" y="23.5" />
      <ClearingCoordinates clearing="5" x="74.3" y="34.9" />
      <PathArc path="1" from="1" to="4" arc1="47.3" arc2="47.3" />
      <PathArc path="5" from="4" to="NW" arc1="20.3" arc2="31.9" />
      <PathArc path="6" from="4" to="N" arc1="50.0" arc2="9.5" />
    </NormalSide>
    <EnchantedSide>
      <OffroadCoordinates x="41.9" y="83.9" />
      <ClearingCoordinates clearing="1" x="62.2" y="75.5" />
      <ClearingCoordinates clearing="2" x="27.4" y="68.2" />
      <ClearingCoordinates clearing="4" x="38.7" y="27.9" />
      <ClearingCoordinates clearing="5" x="74.1" y="35.8" />
      <PathArc path="1" from="1" to="SE" arc1="75.8" arc2="67.5" />
      <PathArc path="5" from="4" to="NW" arc1="22.7" arc2="35.1" />
      <PathArc path="6" from="4" to="N" arc1="50.0" arc2="18.1" />
    </EnchantedSide>
  </TileCoordinateData>
  <TileCoordinateData tile="CV">
		<TileImage>curstvalley</TileImage>
		<NormalSide>
      <OffroadCoordinates x="50.6" y="87.4" />
      <ClearingCoordinates clearing="1" x="50.4" y="18.6" />
      <ClearingCoordinates clearing="2" x="26.6" y="33.5" />
      <ClearingCoordinates clearing="4" x="50.6" y="66.8" />
      <ClearingCoordinates clearing="5" x="72.7" y="34.4" />
      <PathArc path="2" from="2" to="5" arc1="48.5" arc2="45.2" />
      <PathArc path="5" from="4" to="SW" arc1="27.0" arc2="65.5" />
      <PathArc path="6" from="4" to="SE" arc1="69.9" arc2="63.6" />
    </NormalSide>
    <EnchantedSide>
      <OffroadCoordinates x="50.8" y="85.0" />
      <ClearingCoordinates clearing="1" x="50.6" y="18.6" />
      <ClearingCoordinates clearing="2" x="28.8" y="35.1" />
      <ClearingCoordinates clearing="4" x="50.0" y="65.7" />
      <ClearingCoordinates clearing="5" x="74.1" y="34.4" />
      <PathArc path="2" from="2" to="5" arc1="48.9" arc2="41.0" />
      <PathArc path="5" from="4" to="SW" arc1="25.8" arc2="67.3" />
      <PathArc path="6" from="4" to="SE" arc1="69.9" arc2="64.5" />
    </EnchantedSide>
</TileCoordinateData>
  <TileCoordinateData tile="DV">
    <TileImage>darkvalley</TileImage>
    <NormalSide>
      <OffroadCoordinates x="49.3" y="81.1" />
      <ClearingCoordinates clearing="1" x="75.8" y="36.1" />
      <ClearingCoordinates clearing="2" x="52.2" y="20.2" />
      <ClearingCoordinates clearing="4" x="39.9" y="60.3" />
      <ClearingCoordinates clearing="5" x="75.4" y="67.3" />
      <PathArc path="2" from="2" to="5" arc1="51.4" arc2="47.7" />
      <PathArc path="6" from="4" to="NW" arc1="25.0" arc2="33.7" />
    </NormalSide>
    <EnchantedSide>
      <OffroadCoordinates x="49.1" y="79.4" />
      <ClearingCoordinates clearing="1" x="71.9" y="35.4" />
      <ClearingCoordinates clearing="2" x="49.5" y="18.8" />
      <ClearingCoordinates clearing="4" x="38.5" y="57.3" />
      <ClearingCoordinates clearing="5" x="72.7" y="65.2" />
      <PathArc path="2" from="2" to="5" arc1="52.8" arc2="47.7" />
      <PathArc path="6" from="4" to="NW" arc1="23.5" arc2="31.0" />
    </EnchantedSide>
  </TileCoordinateData>
  <TileCoordinateData tile="EV">
    <TileImage>evilvalley</TileImage>
    <NormalSide>
      <OffroadCoordinates x="49.7" y="80.1" />
      <ClearingCoordinates clearing="1" x="26.6" y="66.4" />
      <ClearingCoordinates clearing="2" x="27.4" y="35.4" />
      <ClearingCoordinates clearing="4" x="64.9" y="24.2" />
      <ClearingCoordinates clearing="5" x="73.9" y="66.6" />
      <PathArc path="3" from="1" to="4" arc1="50.0" arc2="50.8" />
      <PathArc path="5" from="4" to="N" arc1="48.9" arc2="10.7" />
      <PathArc path="6" from="4" to="NE" arc1="76.6" arc2="29.3" />
    </NormalSide>
    <EnchantedSide>
      <OffroadCoordinates x="57.8" y="82.2" />
      <ClearingCoordinates clearing="1" x="38.7" y="74.1" />
      <ClearingCoordinates clearing="2" x="27.4" y="34.9" />
      <ClearingCoordinates clearing="4" x="62.2" y="26.1" />
      <ClearingCoordinates clearing="5" x="74.3" y="66.4" />
      <PathArc path="1" from="1" to="SW" arc1="20.3" arc2="68.2" />
      <PathArc path="5" from="4" to="N" arc1="48.1" arc2="13.0" />
      <PathArc path="6" from="4" to="NE" arc1="78.2" arc2="30.5" />
    </EnchantedSide>
  </TileCoordinateData>
  <TileCoordinateData tile="LW">
    <TileImage>lindenwoods</TileImage>
    <NormalSide>
      <OffroadCoordinates x="50.6" y="86.0" />
      <ClearingCoordinates clearing="2" x="52.0" y="65.5" />
      <ClearingCoordinates clearing="4" x="26.0" y="34.4" />
      <ClearingCoordinates clearing="5" x="62.0" y="28.6" />
      <PathArc path="2" from="2" to="SW" arc1="25.8" arc2="66.8" />
      <PathArc path="3" from="2" to="SE" arc1="69.3" arc2="63.1" />
      <PathArc path="5" from="5" to="N" arc1="48.5" arc2="11.6" />
      <PathArc path="6" from="5" to="NE" arc1="76.2" arc2="31.9" />
    </NormalSide>
    <EnchantedSide>
      <OffroadCoordinates x="49.1" y="86.4" />
      <ClearingCoordinates clearing="2" x="48.3" y="64.5" />
      <ClearingCoordinates clearing="4" x="25.4" y="32.4" />
      <ClearingCoordinates clearing="5" x="60.4" y="22.8" />
      <PathArc path="1" from="2" to="SW" arc1="23.7" arc2="65.9" />
      <PathArc path="2" from="2" to="SE" arc1="70.3" arc2="64.8" />
      <PathArc path="3" from="4" to="5" arc1="45.1" arc2="36.5" />
      <PathArc path="5" from="5" to="N" arc1="49.1" arc2="10.2" />
      <PathArc path="6" from="5" to="NE" arc1="75.4" arc2="30.7" />
    </EnchantedSide>
  </TileCoordinateData>
  <TileCoordinateData tile="MW">
    <TileImage>maplewoods</TileImage>
    <NormalSide>
      <OffroadCoordinates x="45.5" y="78.7" />
      <ClearingCoordinates clearing="2" x="64.3" y="29.3" />
      <ClearingCoordinates clearing="4" x="75.0" y="66.6" />
      <ClearingCoordinates clearing="5" x="28.2" y="52.4" />
      <PathArc path="1" from="2" to="4" arc1="62.2" arc2="46.1" />
      <PathArc path="2" from="2" to="N" arc1="48.9" arc2="10.7" />
      <PathArc path="3" from="2" to="NE" arc1="79.2" arc2="29.8" />
      <PathArc path="5" from="5" to="SW" arc1="20.9" arc2="69.9" />
      <PathArc path="6" from="5" to="NW" arc1="20.1" arc2="28.2" />
    </NormalSide>
    <EnchantedSide>
      <OffroadCoordinates x="47.7" y="80.1" />
      <ClearingCoordinates clearing="2" x="65.3" y="26.5" />
      <ClearingCoordinates clearing="4" x="75.0" y="65.9" />
      <ClearingCoordinates clearing="5" x="25.8" y="51.2" />
      <PathArc path="1" from="2" to="N" arc1="47.7" arc2="8.3" />
      <PathArc path="2" from="2" to="NE" arc1="77.0" arc2="28.9" />
      <PathArc path="3" from="4" to="5" arc1="47.1" arc2="50.1" />
      <PathArc path="5" from="5" to="SW" arc1="23.9" arc2="70.3" />
      <PathArc path="6" from="5" to="NW" arc1="27.6" arc2="34.9" />
    </EnchantedSide>
  </TileCoordinateData>
  <TileCoordinateData tile="NW">
    <TileImage>nutwoods</TileImage>
    <NormalSide>
      <OffroadCoordinates x="24.7" y="48.7" />
      <ClearingCoordinates clearing="2" x="38.7" y="24.2" />
      <ClearingCoordinates clearing="4" x="72.5" y="30.0" />
      <ClearingCoordinates clearing="5" x="51.6" y="64.5" />
      <PathArc path="1" from="2" to="4" arc1="53.8" arc2="30.5" />
      <PathArc path="2" from="2" to="NW" arc1="20.9" arc2="30.5" />
      <PathArc path="3" from="2" to="N" arc1="50.0" arc2="9.5" />
      <PathArc path="5" from="5" to="SW" arc1="27.4" arc2="67.3" />
      <PathArc path="6" from="5" to="SE" arc1="68.7" arc2="66.4" />
    </NormalSide>
    <EnchantedSide>
      <OffroadCoordinates x="23.7" y="46.8" />
      <ClearingCoordinates clearing="2" x="36.2" y="21.6" />
      <ClearingCoordinates clearing="4" x="72.3" y="32.4" />
      <ClearingCoordinates clearing="5" x="48.7" y="64.8" />
      <PathArc path="1" from="2" to="NW" arc1="21.3" arc2="30.3" />
      <PathArc path="2" from="2" to="N" arc1="50.0" arc2="11.1" />
      <PathArc path="3" from="4" to="5" arc1="55.8" arc2="42.8" />
      <PathArc path="5" from="5" to="SW" arc1="24.1" arc2="65.5" />
      <PathArc path="6" from="5" to="SE" arc1="71.3" arc2="65.9" />
    </EnchantedSide>
  </TileCoordinateData>
  <TileCoordinateData tile="OW">
