=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/Treasures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="MapChits.xsd"/>
    <xs:include schemaLocation="Natives.xsd"/>
    <xs:include schemaLocation="Spells.xsd"/>
    <xs:simpleType name="Treasure">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="TreasureType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="VisitorPrice">
        <xs:simpleContent>
            <xs:extension base="Visitor">
                <xs:attribute name="goldPrice" type="xs:int" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="FamePrice">
        <xs:simpleContent>
            <xs:extension base="NativeGroup">
                <xs:attribute name="famePrice" type="xs:int" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TreasureData">
        <xs:sequence>
            <xs:element name="Name" type="Treasure"/>
            <xs:element name="Type" type="TreasureType"/>
            <xs:element name="Great" type="EmptyType" minOccurs="0"/>
            <xs:element name="Large" type="EmptyType" minOccurs="0"/>
            <xs:element name="Weight" type="xs:token"/>
            <xs:element name="GoldPrice" type="xs:int"/>
            <xs:element name="GoldPriceDestroyed" type="xs:int" minOccurs="0"/>
            <xs:element name="VisitorPrice" type="VisitorPrice" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Fame" type="xs:int"/>
            <xs:element name="Notoriety" type="xs:int"/>
            <xs:element name="FamePrice" type="FamePrice" minOccurs="0"/>
            <xs:element name="ColorMagic" type="ColorMagic" minOccurs="0"/>
            <xs:element name="SpellType" type="RitualMagic" minOccurs="0"/>
            <xs:element name="ReturnTo" type="ItemReturnLocation" minOccurs="0"/>
            <xs:element name="Description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="TreasureDataList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TreasureData" type="TreasureData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/Treasures.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- completely refactor this into small, large, and TWT ? having a single alphabetical list is nice... pretty minor convenience really -->
<TreasureDataList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Treasures.xsd">
    <TreasureData>
        <Name>7 League Boots</Name>
        <Type>Boots</Type>
        <Weight>N</Weight>
        <GoldPrice>5</GoldPrice>
        <Fame>0</Fame>
        <Notoriety>2</Notoriety>
        <Description>Tremendous strength, time number of 5. This card can be used to open the VAULT and CRYPT.&lt;p&gt;This card allows its owner to record an extra phase to do the MOVE activity, even if he is riding a horse.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Alchemist's Mixture</Name>
        <Type>Weapon</Type>
        <Weight>N</Weight>
        <GoldPrice>4</GoldPrice>
        <Fame>0</Fame>
        <Notoriety>0</Notoriety>
        <ReturnTo>Warlock</ReturnTo>
        <Description>This &lt;i&gt;Potion&lt;/i&gt; represents pinches of deadly powder that are thrown at a target. It is a missile weapon, length 11, weight Negligible, impact Medium, with 3 sharpness stars. Once activated, it can attack one target per round of combat until &lt;i&gt;Midnight&lt;/i&gt;, when it expires. It is not limited to the character who activates it - it can be transferred while active.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Amulet</Name>
        <Type>One-use</Type>
        <Weight>N</Weight>
        <GoldPrice>5</GoldPrice>
        <Fame>0</Fame>
        <Notoriety>0</Notoriety>
        <ReturnTo>Shaman</ReturnTo>
        <Description>This card can cure one character in its clearing of one Curse, or, starting in the FOURTH ENCOUNTER, it can break (or partially break) one spell whose spellcaster or target is in his clearing. The card's owner chooses exactly which Curse (or spell) is cancelled. At &lt;i&gt;Midnight&lt;/i&gt; it returns to the SHAMAN's box.&lt;p&gt;&lt;b&gt;1.&lt;/b&gt; The AMULET can break one curse on one character. Other characters and other Curses are not affected.&lt;p&gt;&lt;b&gt;2.&lt;/b&gt; When used against a spell, the AMULET functions like a spellbreaking spell (see rule 44.5). It releases some or all of the spell's targets from the spell. It can be used against a spell only if the spell already exists at the moment the AMULET is activated - it cannot affect a spellthat is in the process of being cast. The AMULET affects only one spell - duplicates of the spell are not affected.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Ancient Telescope</Name>
        <Type>Birdsong</Type>
        <Weight>N</Weight>
        <GoldPrice>5</GoldPrice>
        <Fame>0</Fame>
        <Notoriety>0</Notoriety>
        <Description>This card gives its owner an extra phase that he can use to PEER from one mountain clearing to any other mountain clearing. It gives him one extra phase that he can use to do the enhanced PEER activity. When he records the activity he must record the mountain clearing he will search. When he does the activity he must be in a mountain clearing or the activity is cancelled.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Battle Bracelets</Name>
        <Type>Combat effect</Type>
        <Large/>
        <Weight>N</Weight>
        <GoldPrice>12</GoldPrice>
        <Fame>2</Fame>
        <Notoriety>4</Notoriety>
        <Description>If he is attacking a target whose maneuver time is 5 or more, he can shift his attack to any &lt;i&gt;Attack&lt;/&gt; circle he chooses. If his target's maneuver is 4 or less, he cannot shift his attack. &lt;i&gt;Note:&lt;/i&gt; If he is attacking multiple targets, he can shift his attack only if every target has a maneuver time of 5 or more.&lt;p&gt;&lt;b&gt;*&lt;/b&gt; If the BATTLE BRACELETS and ELUSIVE CLOAK are used in the same melee step, the attack is shifted first, then the maneuver.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Beast Pipes</Name>
        <Type>Artifact</Type>
        <Weight>N</Weight>
        <GoldPrice>8</GoldPrice>
        <VisitorPrice goldPrice="20">Scholar</VisitorPrice>
        <VisitorPrice goldPrice="20">Crone</VisitorPrice>
        <Fame>-5</Fame>
        <Notoriety>5</Notoriety>
        <SpellType>VIII</SpellType>
        <Description>This card contains one type VIII Spell card. It can be used as a MAGIC-VIII-0 chit to cast this spell.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Bejeweled Dwarf Vest</Name>
        <Type>Armor</Type>
        <Great/>
        <Large/>
        <Weight>M</Weight>
        <GoldPrice>27</GoldPrice>
        <GoldPriceDestroyed>22</GoldPriceDestroyed>
        <Fame>0</Fame>
        <Notoriety>5</Notoriety>
        <FamePrice famePrice="10">Soldiers</FamePrice>
        <Description>When active, this card intercepts &lt;i&gt;Thrust&lt;/i&gt; attacks. It is destroyed when Heavy (or greater) harm is inflicted on it. When it is destroyed, the owner gets 23 GOLD points to represent the value of its jewels.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Belt of Strength</Name>
        <Type>Altering action chits</Type>
        <Large/>
        <Weight>N</Weight>
        <GoldPrice>16</GoldPrice>
        <Fame>3</Fame>
        <Notoriety>6</Notoriety>
        <Description>This card alters the strength of its owner's MOVE, FIGHT, DUCK and BERSERK chits (his MAGIC chits are not affected). The asterisks on each chit define its strength: each chit with two asterisks has Tremendous strength, each chit with one asterisk has Heavy strength, and each chit with no asterisks has Medium strength.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Black Book</Name>
        <Type>Spell Book</Type>
        <Great/>
        <Weight>L</Weight>
        <GoldPrice>10</GoldPrice>
        <VisitorPrice goldPrice="50">Scholar</VisitorPrice>
        <VisitorPrice goldPrice="50">Crone</VisitorPrice>
        <Fame>-15</Fame>
        <Notoriety>15</Notoriety>
        <SpellType>V</SpellType>
        <Description>This card contains two type V Spell cards and two type VIII Spell cards. Once per day it can be used as a MAGIC-V-0 chit to cast one of the type V spells. It cannot cast the type VIII spells.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Blasted Jewel</Name>
        <Type>Artifact</Type>
        <Great/>
        <Large/>
        <Weight>H</Weight>
        <GoldPrice>30</GoldPrice>
        <VisitorPrice goldPrice="20">Scholar</VisitorPrice>
        <Fame>-15</Fame>
        <Notoriety>15</Notoriety>
        <SpellType>V</SpellType>
        <Description>This card contains one type V Spell card. Once per day it can be used as a MAGIC-V-0 chit to cast this spell.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Book of Lore</Name>
        <Type>Spell Book</Type>
        <Weight>L</Weight>
        <GoldPrice>10</GoldPrice>
        <VisitorPrice goldPrice="50">Scholar</VisitorPrice>
        <Fame>-5</Fame>
        <Notoriety>10</Notoriety>
        <SpellType>IV</SpellType>
        <Description>This card contains four type IV Spells. Once per day it can be used as a MAGIC-IV-0 chit to cast one of them.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Chest</Name>
        <Type>Substitute</Type>
        <Weight>T</Weight>
        <GoldPrice>0</GoldPrice>
        <GoldPriceDestroyed>0</GoldPriceDestroyed>
        <Fame>0</Fame>
        <Notoriety>0</Notoriety>
        <Description>The only way to exchange the chest is with the LOST KEYS; it stays in play like any other item until it is exchanged. A character can activate the CHEST only if he has the LOST KEYS active. When he activates the CHEST, he immediately exchanges for its treasures. He keeps the treasures and adds 50 points to his recorded GOLD. &lt;i&gt;Note:&lt;/i&gt; The CHEST cannot be reused once it is exchanged.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Cloak of Mist</Name>
        <Type>Birdsong</Type>
        <Weight>N</Weight>
        <GoldPrice>4</GoldPrice>
        <Fame>0</Fame>
        <Notoriety>2</Notoriety>
        <Description>This card allows its owner to record an extra phase to do the HIDE activity.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Cloven Hoof</Name>
        <Type>Enchanted</Type>
        <Great/>
        <Weight>N</Weight>
        <GoldPrice>4</GoldPrice>
        <Fame>-20</Fame>
        <Notoriety>40</Notoriety>
        <ColorMagic>BLACK</ColorMagic>
        <Description>This card affects all tables, and it is an Enchanted card that affects every character in its clearing.Whenever a character rolls on any table while he is in the same clearing with the CLOVEN HOOF, he adds one to his result. Starting in the FOURTH ENCOUNTER, this card is also a sourceof &lt;i&gt;BLACK color&lt;/i&gt; magic to everyone in its clearing.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Crypt of the Knight</Name>
        <Type>Site</Type>
        <Weight>T+</Weight>
        <GoldPrice>0</GoldPrice>
        <GoldPriceDestroyed>0</GoldPriceDestroyed>
        <Fame>0</Fame>
        <Notoriety>0</Notoriety>
        <Description>Roll on site table.</Description>
    </TreasureData>
    <TreasureData>
        <Name>Crystal Ball</Name>
        <Type>Birdsong</Type>
        <Large/>
        <Weight>M</Weight>
        <GoldPrice>20</GoldPrice>
        <Fame>0</Fame>
        <Notoriety>5</Notoriety>
