=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/HorseTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="MiscTypes.xsd"/>
    <xs:simpleType name="HorseType">
        <xs:restriction base="xs:token"/>
    </xs:simpleType>
    <xs:simpleType name="HorseMoveValue">
        <xs:restriction base="xs:token"/>
    </xs:simpleType>
    <xs:complexType name="HorseTypeData">
        <xs:sequence>
            <xs:element name="Name" type="HorseType"/>
            <xs:element name="Vulnerability" type="Weight"/>
            <xs:element name="Armored" type="xs:boolean"/>
            <xs:element name="MoveBonus" type="NonEmptyString"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="HorseTypeDataList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="HorseTypeData" type="HorseTypeData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/HorseTypes.xml
<?xml version="1.0" encoding="utf-8"?>
<HorseTypeDataList
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    
    xsi:noNamespaceSchemaLocation="HorseTypes.xsd">

  <HorseTypeData>
    <Name>Pony</Name>
    <Vulnerability>M</Vulnerability>
    <Armored>0</Armored>
    <MoveBonus>*2</MoveBonus>
  </HorseTypeData>
  <HorseTypeData>
    <Name>Workhorse</Name>
    <Vulnerability>H</Vulnerability>
    <Armored>0</Armored>
    <MoveBonus>+1</MoveBonus>
  </HorseTypeData>
  <HorseTypeData>
    <Name>Warhorse</Name>
    <Vulnerability>T</Vulnerability>
    <Armored>1</Armored>
    <MoveBonus>0</MoveBonus>
  </HorseTypeData>
</HorseTypeDataList>
