=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/Horses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="HorseTypes.xsd"/>
    <!-- 
        refer to horse by type and id; eg: <Pony>1</Pony>  
    -->
    <xs:simpleType name="HorseId">
        <xs:restriction base="xs:int"/>
    </xs:simpleType>
    <xs:element name="Horse" type="HorseId" abstract="true"/>
    <xs:element name="Pony" substitutionGroup="Horse">
        <xs:simpleType>
            <xs:restriction base="HorseId"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Warhorse" substitutionGroup="Horse">
        <xs:simpleType>
            <xs:restriction base="HorseId"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Workhorse" substitutionGroup="Horse">
        <xs:simpleType>
            <xs:restriction base="HorseId"/>
        </xs:simpleType>
    </xs:element>
    <!--
         todo - is there a better way to inherit this data?
        want to refer to horses via <Pony>1</Pony> ?
     -->
    <xs:complexType name="HorseData">
        <xs:sequence>
            <xs:element name="ID" type="HorseId"/>
            <xs:element name="Gallop" type="HorseMoveValue"/>
            <xs:element name="Walk" type="HorseMoveValue"/>
            <xs:element name="Price" type="GoldPrice"/>
            <xs:element name="StartingLocation" type="ItemStartingLocation"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="HorseDataBase" type="HorseData" abstract="true"/>
    <xs:element name="PonyData" substitutionGroup="HorseDataBase">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="HorseData"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="WorkhorseData" substitutionGroup="HorseDataBase">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="HorseData"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="WarhorseData" substitutionGroup="HorseDataBase">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="HorseData"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Horses">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="HorseDataBase" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/Horses.xml
<?xml version="1.0" encoding="utf-8"?>
<Horses
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    
    xsi:noNamespaceSchemaLocation="Horses.xsd">

  <PonyData>
    <ID>1</ID>
    <Gallop>L2</Gallop>
    <Walk>L4</Walk>
    <Price>16</Price>
    <StartingLocation>Enchanted Meadow</StartingLocation>
  </PonyData>
  <PonyData>
    <ID>2</ID>
    <Gallop>M2</Gallop>
    <Walk>M5</Walk>
    <Price>16</Price>
    <StartingLocation>Bashkars</StartingLocation>
  </PonyData>
  <PonyData>
    <ID>3</ID>
    <Gallop>M3</Gallop>
    <Walk>M4</Walk>
    <Price>15</Price>
    <StartingLocation>Bashkars</StartingLocation>
  </PonyData>
  <PonyData>
    <ID>4</ID>
    <Gallop>M3</Gallop>
    <Walk>M5</Walk>
    <Price>14</Price>
    <StartingLocation>Bashkars</StartingLocation>
  </PonyData>
  <PonyData>
    <ID>5</ID>
    <Gallop>L3</Gallop>
    <Walk>M4</Walk>
    <Price>14</Price>
    <StartingLocation>Bashkars</StartingLocation>
  </PonyData>
  <PonyData>
    <ID>6</ID>
    <Gallop>L3</Gallop>
    <Walk>M5</Walk>
    <Price>12</Price>
    <StartingLocation>Bashkars</StartingLocation>
  </PonyData>
  <PonyData>
    <ID>7</ID>
    <Gallop>M4</Gallop>
    <Walk>M5</Walk>
    <Price>12</Price>
    <StartingLocation>Bashkars</StartingLocation>
  </PonyData>

  <WorkhorseData>
    <ID>1</ID>
    <Gallop>H6</Gallop>
    <Walk>T8</Walk>
    <Price>12</Price>
    <StartingLocation>Rogues</StartingLocation>
  </WorkhorseData>
  <WorkhorseData>
    <ID>2</ID>
    <Gallop>H6</Gallop>
    <Walk>H7</Walk>
    <Price>11</Price>
    <StartingLocation>Rogues</StartingLocation>
  </WorkhorseData>
  <WorkhorseData>
    <ID>3</ID>
    <Gallop>M5</Gallop>
    <Walk>H7</Walk>
    <Price>11</Price>
    <StartingLocation>Rogues</StartingLocation>
  </WorkhorseData>
  <WorkhorseData>
    <ID>4</ID>
    <Gallop>M5</Gallop>
    <Walk>M6</Walk>
    <Price>10</Price>
    <StartingLocation>Rogues</StartingLocation>
  </WorkhorseData>
  <WorkhorseData>
    <ID>5</ID>
    <Gallop>L4</Gallop>
    <Walk>M6</Walk>
    <Price>9</Price>
    <StartingLocation>Rogues</StartingLocation>
  </WorkhorseData>
  <WorkhorseData>
    <ID>6</ID>
    <Gallop>L4</Gallop>
    <Walk>L5</Walk>
    <Price>8</Price>
    <StartingLocation>Rogues</StartingLocation>
  </WorkhorseData>
  
  <WarhorseData>
    <ID>1</ID>
    <Gallop>T3</Gallop>
    <Walk>T5</Walk>
    <Price>25</Price>
    <StartingLocation>Crypt of the Knight</StartingLocation>
  </WarhorseData>
  <WarhorseData>
    <ID>2</ID>
    <Gallop>T5</Gallop>
    <Walk>T7</Walk>
    <Price>22</Price>
    <StartingLocation>Order</StartingLocation>
  </WarhorseData>
  <WarhorseData>
    <ID>3</ID>
    <Gallop>H4</Gallop>
    <Walk>T7</Walk>
    <Price>20</Price>
    <StartingLocation>Order</StartingLocation>
  </WarhorseData>
  <WarhorseData>
    <ID>4</ID>
    <Gallop>H4</Gallop>
    <Walk>H6</Walk>
    <Price>18</Price>
    <StartingLocation>Order</StartingLocation>
  </WarhorseData>
</Horses>
