=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/MapChits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="Tiles.xsd"/>
    <xs:include schemaLocation="Missions.xsd"/>
    <xs:include schemaLocation="Campaigns.xsd"/>
    <xs:complexType name="SoundChit">
        <xs:sequence>
            <xs:element name="Name" type="SoundType"/>
            <xs:element name="Clearing" type="Clearing"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SoundChits">
        <xs:sequence>
            <xs:element name="SoundChit" type="SoundChit" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="WarningChit">
        <xs:sequence>
            <xs:element name="Name" type="WarningType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="WarningChits">
        <xs:sequence>
            <xs:element name="WarningChit" type="WarningChit" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SoundOrWarningChit">
        <xs:simpleContent>
            <xs:extension base="NonEmptyString">
                <xs:attribute name="type" type="TileType" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="SubstituteChit">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    
    <xs:group name="SiteAndSoundChitLocationType">
        <xs:choice>
            <xs:element name="TileType" type="TileType"/>
            <xs:element name="SubstituteChitType" type="SubstituteChit"/>
        </xs:choice>
    </xs:group>
    
    <xs:complexType name="SiteAndSoundChitLocation">
        <xs:sequence>
            <xs:group ref="SiteAndSoundChitLocationType"/>
            <xs:element name="SiteAndSoundChits" type="xs:int"/>
            <xs:element name="SubstituteChitRef" type="SubstituteChit" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SiteAndSoundChitLocations">
        <xs:sequence>
            <xs:element name="SiteAndSoundChitLocation" type="SiteAndSoundChitLocation" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <xs:complexType name="TreasureSiteChit">
        <xs:sequence>
            <xs:element name="Name" type="TreasureSite"/>
            <xs:element name="Clearing" type="Clearing"/>
            <xs:element name="SmallTreasures" type="xs:int"/>
            <xs:element name="LargeTreasures" type="xs:int"/>
            <xs:element name="Monster" type="Monster"/>
            <xs:element name="MonsterRoll" type="MonsterRoll"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TreasureSiteChits">
        <xs:sequence>
            <xs:element name="TreasureSiteChit" type="TreasureSiteChit" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="DwellingData">
        <xs:sequence>
            <xs:element name="Name" type="Dwelling"/>
            <xs:element name="MapChit" type="SoundOrWarningChit"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DwellingDataList">
        <xs:sequence>
            <xs:element name="DwellingData" type="DwellingData" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:group name="VisitorMissionCampaignChitSide">
        <xs:choice>
            <xs:element name="Visitor" type="Visitor"/>
            <xs:element name="Mission" type="Mission"/>
            <xs:element name="Campaign" type="Campaign"/>
        </xs:choice>
    </xs:group>
    <xs:complexType name="VisitorMissionCampaignChit">
        <xs:sequence>
            <xs:group ref="VisitorMissionCampaignChitSide" minOccurs="2" maxOccurs="2"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="VisitorMissionCampaignChits">
        <xs:sequence>
            <xs:element name="VisitorMissionCampaignChit" type="VisitorMissionCampaignChit" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="MapChitData">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SoundChits" type="SoundChits"/>
                <xs:element name="WarningChits" type="WarningChits"/>
                <xs:element name="TreasureSiteChits" type="TreasureSiteChits"/>
                <xs:element name="SiteAndSoundChitLocations" type="SiteAndSoundChitLocations"/>
                <xs:element name="DwellingDataList" type="DwellingDataList"/>
                <xs:element name="VisitorMissionCampaignChits" type="VisitorMissionCampaignChits"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/MapChits.xml
<?xml version="1.0" encoding="utf-8"?><MapChitData      xmlns:xsd="http://www.w3.org/2001/XMLSchema"       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"          xsi:noNamespaceSchemaLocation="MapChits.xsd">     <SoundChits>        <SoundChit>            <Name>Flutter</Name>            <Clearing>1</Clearing>        </SoundChit>        <SoundChit>            <Name>Flutter</Name>            <Clearing>2</Clearing>        </SoundChit>        <SoundChit>            <Name>Howl</Name>            <Clearing>4</Clearing>        </SoundChit>        <SoundChit>            <Name>Howl</Name>            <Clearing>5</Clearing>        </SoundChit>        <SoundChit>            <Name>Patter</Name>            <Clearing>2</Clearing>        </SoundChit>        <SoundChit>            <Name>Patter</Name>            <Clearing>5</Clearing>        </SoundChit>        <SoundChit>            <Name>Roar</Name>            <Clearing>4</Clearing>        </SoundChit>        <SoundChit>            <Name>Roar</Name>            <Clearing>6</Clearing>        </SoundChit>        <SoundChit>            <Name>Slither</Name>            <Clearing>3</Clearing>        </SoundChit>        <SoundChit>            <Name>Slither</Name>            <Clearing>6</Clearing>        </SoundChit>    </SoundChits>    <WarningChits>        <WarningChit>            <Name>Bones</Name>        </WarningChit>        <WarningChit>            <Name>Dank</Name>        </WarningChit>        <WarningChit>            <Name>Ruins</Name>        </WarningChit>        <WarningChit>            <Name>Smoke</Name>        </WarningChit>        <WarningChit>            <Name>Stink</Name>        </WarningChit>    </WarningChits>        <TreasureSiteChits>        <TreasureSiteChit>            <Name>Altar</Name>            <Clearing>1</Clearing>            <SmallTreasures>0</SmallTreasures>            <LargeTreasures>4</LargeTreasures>            <Monster>Demon</Monster>            <MonsterRoll>2</MonsterRoll>        </TreasureSiteChit>        <TreasureSiteChit>            <Name>Cairns</Name>            <Clearing>5</Clearing>            <SmallTreasures>6</SmallTreasures>            <LargeTreasures>1</LargeTreasures>            <Monster>T Spider</Monster>            <MonsterRoll>5</MonsterRoll>        </TreasureSiteChit>        <TreasureSiteChit>            <Name>Hoard</Name>            <Clearing>6</Clearing>            <SmallTreasures>4</SmallTreasures>            <LargeTreasures>5</LargeTreasures>            <Monster>T Flying Dragon</Monster>            <MonsterRoll>1</MonsterRoll>        </TreasureSiteChit>        <TreasureSiteChit>            <Name>Lair</Name>            <Clearing>3</Clearing>            <SmallTreasures>4</SmallTreasures>            <LargeTreasures>3</LargeTreasures>            <Monster>T Dragon</Monster>            <MonsterRoll>1</MonsterRoll>        </TreasureSiteChit>        <TreasureSiteChit>            <Name>Pool</Name>            <Clearing>6</Clearing>            <SmallTreasures>6</SmallTreasures>            <LargeTreasures>3</LargeTreasures>            <Monster>Octopus</Monster>            <MonsterRoll>3</MonsterRoll>        </TreasureSiteChit>        <TreasureSiteChit>            <Name>Shrine</Name>            <Clearing>4</Clearing>            <SmallTreasures>2</SmallTreasures>            <LargeTreasures>2</LargeTreasures>            <Monster>Winged Demon</Monster>            <MonsterRoll>2</MonsterRoll>        </TreasureSiteChit>        <TreasureSiteChit>            <Name>Statue</Name>            <Clearing>2</Clearing>            <SmallTreasures>2</SmallTreasures>            <LargeTreasures>1</LargeTreasures>            <Monster>Imp</Monster>            <MonsterRoll>5</MonsterRoll>        </TreasureSiteChit>        <TreasureSiteChit>            <Name>Vault</Name>            <Clearing>3</Clearing>            <SmallTreasures>0</SmallTreasures>            <LargeTreasures>5</LargeTreasures>            <Monster>T Troll</Monster>            <MonsterRoll>4</MonsterRoll>        </TreasureSiteChit>    </TreasureSiteChits>    <SiteAndSoundChitLocations>        <SiteAndSoundChitLocation>            <TileType>C</TileType>            <SiteAndSoundChits>4</SiteAndSoundChits>            <SubstituteChitRef>LostCity</SubstituteChitRef>        </SiteAndSoundChitLocation>        <SiteAndSoundChitLocation>            <TileType>M</TileType>            <SiteAndSoundChits>4</SiteAndSoundChits>            <SubstituteChitRef>LostCastle</SubstituteChitRef>        </SiteAndSoundChitLocation>        <SiteAndSoundChitLocation>            <SubstituteChitType>LostCity</SubstituteChitType>            <SiteAndSoundChits>5</SiteAndSoundChits>        </SiteAndSoundChitLocation>        <SiteAndSoundChitLocation>            <SubstituteChitType>LostCastle</SubstituteChitType>            <SiteAndSoundChits>5</SiteAndSoundChits>        </SiteAndSoundChitLocation>    </SiteAndSoundChitLocations>    <DwellingDataList>        <DwellingData>          <Name>Chapel</Name>          <MapChit type="V">Dank</MapChit>        </DwellingData>        <DwellingData>          <Name>Ghost Clearing</Name>          <MapChit type="V">Bones</MapChit>        </DwellingData>        <DwellingData>          <Name>Guardhouse</Name>          <MapChit type="V">Ruins</MapChit>        </DwellingData>        <DwellingData>          <Name>House</Name>          <MapChit type="V">Smoke</MapChit>        </DwellingData>        <DwellingData>          <Name>Inn</Name>          <MapChit type="V">Stink</MapChit>        </DwellingData>        <DwellingData>          <Name>Large Campfire</Name>          <MapChit type="W">Stink</MapChit>        </DwellingData>        <DwellingData>          <Name>Small Campfire</Name>          <MapChit type="W">Smoke</MapChit>        </DwellingData>    </DwellingDataList>        <VisitorMissionCampaignChits>        <VisitorMissionCampaignChit>                <Visitor>Shaman</Visitor>                <Mission>Escort Party</Mission>        </VisitorMissionCampaignChit>            <VisitorMissionCampaignChit>                <Visitor>Warlock</Visitor>                <Mission>Food/Ale</Mission>        </VisitorMissionCampaignChit>        <VisitorMissionCampaignChit>                <Visitor>Crone</Visitor>                <Campaign>Raid</Campaign>        </VisitorMissionCampaignChit>        <VisitorMissionCampaignChit>                <Visitor>Scholar</Visitor>                <Campaign>Pilliage</Campaign>        </VisitorMissionCampaignChit>        <VisitorMissionCampaignChit>                <Campaign>Conquer</Campaign>                <Campaign>War</Campaign>        </VisitorMissionCampaignChit>        <VisitorMissionCampaignChit>                <Campaign>Revolt</Campaign>                <Campaign>Quest</Campaign>        </VisitorMissionCampaignChit>    </VisitorMissionCampaignChits></MapChitData>
