=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/Natives.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="HorseTypes.xsd"/>
    <xs:simpleType name="NativeColor">
        <xs:restriction base="NonEmptyToken"/>
    </xs:simpleType>
    <xs:simpleType name="NativeId">
        <xs:restriction base="NonEmptyToken"/>
    </xs:simpleType>
    <xs:simpleType name="NativeType">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    <xs:simpleType name="NativeAttackValue">
        <xs:restriction base="NonEmptyString"/>
    </xs:simpleType>
    <xs:simpleType name="NativeMoveTime">
        <xs:restriction base="xs:int"/>
    </xs:simpleType>
    <xs:complexType name="NativeCombatStats">
        <xs:sequence>
            <xs:element name="Attack" type="NativeAttackValue"/>
            <xs:element name="MoveTime" type="NativeMoveTime"/>
            <!-- MoveStrength defined in NativeTypes -->
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NativeHorseData">
        <xs:sequence>
            <xs:element name="Type" type="HorseType"/>
            <xs:element name="Gallop" type="HorseMoveValue"/>
            <xs:element name="Walk" type="HorseMoveValue"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NativeData">
        <xs:sequence>
            <xs:element name="ID" type="NativeId"/>
            <xs:element name="Type" type="NativeType"/>
            <xs:element name="Unalerted" type="NativeCombatStats"/>
            <xs:element name="Alerted" type="NativeCombatStats"/>
            <xs:element name="Horse" type="NativeHorseData" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NativeGroupData">
        <xs:sequence>
            <xs:element name="Name" type="NativeGroup"/>
            <xs:element name="HireIndividually" type="xs:boolean"/>
            <xs:element name="Color" type="NativeColor"/>
            <xs:element name="Garrison" type="Dwelling" minOccurs="0"/>
            <xs:element name="NativeData" type="NativeData" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="NativeGroupDataList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NativeGroupData" type="NativeGroupData" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/Natives.xml
<?xml version="1.0" encoding="utf-8"?>
<NativeGroupDataList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Natives.xsd">
    <!-- todo: assumed crossbowmen have an alerted attack of H1* instead of H1 -->
    <NativeGroupData>
        <Name>Bashkars</Name>
        <HireIndividually>false</HireIndividually>
        <Color>Red</Color>
        <NativeData>
            <ID>BHQ</ID>
            <Type>Raider</Type>
            <Unalerted>
                <Attack>L4*</Attack>
                <MoveTime>2</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>M4*</Attack>
                <MoveTime>3</MoveTime>
            </Alerted>
            <Horse>
                <Type>Pony</Type>
                <Gallop>M3</Gallop>
                <Walk>M4</Walk>
            </Horse>
        </NativeData>
        <NativeData>
            <ID>B1</ID>
            <Type>Raider</Type>
            <Unalerted>
                <Attack>M3*</Attack>
                <MoveTime>3</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>L3*</Attack>
                <MoveTime>3</MoveTime>
            </Alerted>
            <Horse>
                <Type>Pony</Type>
                <Gallop>M3</Gallop>
                <Walk>M5</Walk>
            </Horse>
        </NativeData>
        <NativeData>
            <ID>B2</ID>
            <Type>Raider</Type>
            <Unalerted>
                <Attack>M4*</Attack>
                <MoveTime>2</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>L3*</Attack>
                <MoveTime>3</MoveTime>
            </Alerted>
            <Horse>
                <Type>Pony</Type>
                <Gallop>M4</Gallop>
                <Walk>M5</Walk>
            </Horse>
        </NativeData>

        <NativeData>
            <ID>B3</ID>
            <Type>Raider</Type>
            <Unalerted>
                <Attack>L4*</Attack>
                <MoveTime>2</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>M3*</Attack>
                <MoveTime>4</MoveTime>
            </Alerted>
            <Horse>
                <Type>Pony</Type>
                <Gallop>M4</Gallop>
                <Walk>L3</Walk>
            </Horse>
        </NativeData>
        <NativeData>
            <ID>B4</ID>
            <Type>Raider</Type>
            <Unalerted>
                <Attack>M5*</Attack>
                <MoveTime>2</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>L2*</Attack>
                <MoveTime>4</MoveTime>
            </Alerted>
            <Horse>
                <Type>Pony</Type>
                <Gallop>M5</Gallop>
                <Walk>L3</Walk>
            </Horse>
        </NativeData>
        <NativeData>
            <ID>B5</ID>
            <Type>Raider</Type>
            <Unalerted>
                <Attack>L2*</Attack>
                <MoveTime>4</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>L2*</Attack>
                <MoveTime>4</MoveTime>
            </Alerted>
            <Horse>
                <Type>Pony</Type>
                <Gallop>L5</Gallop>
                <Walk>M2</Walk>
            </Horse>
        </NativeData>

    </NativeGroupData>
    <NativeGroupData>
        <Name>Company</Name>
        <HireIndividually>false</HireIndividually>
        <Color>Blue</Color>
        <NativeData>
            <ID>CHQ</ID>
            <Type>Short Swordsman</Type>
            <Unalerted>
                <Attack>M3*</Attack>
                <MoveTime>5</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>L4*</Attack>
                <MoveTime>3</MoveTime>
            </Alerted>
        </NativeData>
        <NativeData>
            <ID>C1</ID>
            <Type>Short Swordsman</Type>
            <Unalerted>
                <Attack>L3*</Attack>
                <MoveTime>4</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>M4*</Attack>
                <MoveTime>3</MoveTime>
            </Alerted>
        </NativeData>
        <NativeData>
            <ID>C2</ID>
            <Type>Pikeman</Type>
            <Unalerted>
                <Attack>H6*</Attack>
                <MoveTime>4</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>M4*</Attack>
                <MoveTime>5</MoveTime>
            </Alerted>
        </NativeData>
        <NativeData>
            <ID>C3</ID>
            <Type>Pikeman</Type>
            <Unalerted>
                <Attack>H6*</Attack>
                <MoveTime>4</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>M4*</Attack>
                <MoveTime>5</MoveTime>
            </Alerted>
        </NativeData>
        <NativeData>
            <ID>C4</ID>
            <Type>Pikeman</Type>
            <Unalerted>
                <Attack>H6*</Attack>
                <MoveTime>4</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>M4*</Attack>
                <MoveTime>5</MoveTime>
            </Alerted>
        </NativeData>
        <NativeData>
            <ID>C5</ID>
            <Type>Great Swordsman</Type>
            <Unalerted>
                <Attack>T4*</Attack>
                <MoveTime>6</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>H5*</Attack>
                <MoveTime>5</MoveTime>
            </Alerted>
        </NativeData>
        <NativeData>
            <ID>C6</ID>
            <Type>Crossbowman</Type>
            <Unalerted>
                <Attack>H6</Attack>
                <MoveTime>5</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>H1*</Attack>
                <MoveTime>4</MoveTime>
            </Alerted>
        </NativeData>
    </NativeGroupData>
    <NativeGroupData>
        <Name>Guard</Name>
        <HireIndividually>false</HireIndividually>
        <Color>Gold</Color>
        <Garrison>Guardhouse</Garrison>
        <NativeData>
            <ID>GHQ</ID>
            <Type>Great Swordsman</Type>
            <Unalerted>
                <Attack>H5*</Attack>
                <MoveTime>5</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>T4*</Attack>
                <MoveTime>6</MoveTime>
            </Alerted>
        </NativeData>
        <NativeData>
            <ID>G1</ID>
            <Type>Great Swordsman</Type>
            <Unalerted>
                <Attack>H5*</Attack>
                <MoveTime>5</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>T4*</Attack>
                <MoveTime>6</MoveTime>
            </Alerted>
        </NativeData>
        <NativeData>
            <ID>G2</ID>
            <Type>Great Swordsman</Type>
            <Unalerted>
                <Attack>H5*</Attack>
                <MoveTime>5</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>T4*</Attack>
                <MoveTime>6</MoveTime>
            </Alerted>
        </NativeData>
    </NativeGroupData>
    <NativeGroupData>
        <Name>Lancers</Name>
        <HireIndividually>false</HireIndividually>
        <Color>Green</Color>
        <NativeData>
            <ID>LHQ</ID>
            <Type>Lancer</Type>
            <Unalerted>
                <Attack>H5*</Attack>
                <MoveTime>3</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>M3*</Attack>
                <MoveTime>4</MoveTime>
            </Alerted>
            <Horse>
                <Type>Pony</Type>
                <Gallop>M4</Gallop>
                <Walk>M3</Walk>
            </Horse>
        </NativeData>
        <NativeData>
            <ID>L1</ID>
            <Type>Lancer</Type>
            <Unalerted>
                <Attack>H6*</Attack>
                <MoveTime>2</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>M3*</Attack>
                <MoveTime>4</MoveTime>
            </Alerted>
            <Horse>
                <Type>Pony</Type>
                <Gallop>M5</Gallop>
                <Walk>M3</Walk>
            </Horse>
        </NativeData>
        <NativeData>
            <ID>L2</ID>
            <Type>Lancer</Type>
            <Unalerted>
                <Attack>M4*</Attack>
                <MoveTime>3</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>H4*</Attack>
                <MoveTime>4</MoveTime>
            </Alerted>
            <Horse>
                <Type>Pony</Type>
                <Gallop>M5</Gallop>
                <Walk>M4</Walk>
            </Horse>
        </NativeData>
        <NativeData>
            <ID>L3</ID>
            <Type>Lancer</Type>
            <Unalerted>
                <Attack>H4*</Attack>
                <MoveTime>5</MoveTime>
            </Unalerted>
            <Alerted>
                <Attack>M4*</Attack>
                <MoveTime>4</MoveTime>
            </Alerted>
            <Horse>
                <Type>Pony</Type>
                <Gallop>L4</Gallop>
                <Walk>L2</Walk>
            </Horse>
        </NativeData>
    </NativeGroupData>
    <NativeGroupData>
        <Name>Order</Name>
        <HireIndividually>true</HireIndividually>
        <Color>Gold</Color>
        <Garrison>Chapel</Garrison>
        <NativeData>
            <ID>OHQ</ID>
            <Type>Knight</Type>
            <Unalerted>
                <Attack>H6*</Attack>
