=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/PlayerCharacters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="Armor.xsd"/>
    <xs:include schemaLocation="Weapons.xsd"/>
    <xs:include schemaLocation="Horses.xsd"/>
    <xs:include schemaLocation="Spells.xsd"/>
    <xs:include schemaLocation="Treasures.xsd"/>
    <xs:include schemaLocation="Tiles.xsd"/>
    <xs:include schemaLocation="Missions.xsd"/>
    <xs:include schemaLocation="Campaigns.xsd"/>
    <xs:group name="ActiveBelonging">
        <xs:choice>
            <!-- todo Armor types must be unique! -->
            <!-- also, only a single boots card, gloves card, ?? can be active at a time -->
            <!-- most of these checks will be done outside of XML -->
            <xs:element name="Armor" type="Armor"/>
            <xs:element name="Treasure" type="Treasure"/>
        </xs:choice>
    </xs:group>
    <xs:complexType name="ActiveBelongings">
        <xs:sequence>
            <xs:element name="Weapon" minOccurs="0">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="Weapon">
                            <xs:attribute ref="alerted" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element ref="Horse" minOccurs="0"/>
            <xs:group ref="ActiveBelonging" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:group name="InactiveBelonging">
        <xs:choice>
            <xs:element name="Armor" type="Armor"/>
            <xs:element name="Weapon" type="Weapon"/>
            <xs:element name="Treasure" type="Treasure"/>
            <xs:element ref="Horse"/>
        </xs:choice>
    </xs:group>
    <xs:complexType name="InactiveBelongings">
        <xs:sequence>
            <xs:group ref="InactiveBelonging" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- todo remove choice ? -->
    <xs:group name="Discovery">
        <xs:choice>
            <!-- todo: try CL25 multi-part key ?? -->
            <xs:element name="HiddenPath" type="Path"/>
            <!-- todo CR16 -->
            <xs:element name="SecretPassage" type="Path"/>
            <xs:element name="TreasureSites" type="TreasureSites"/>
            <xs:element name="TreasuresWithinTreasureSites" type="TreasureSiteCards"/>
            <xs:element name="Caches" type="CacheId"/>
        </xs:choice>
    </xs:group>
    <xs:complexType name="Discoveries">
        <xs:sequence>
            <xs:group ref="Discovery" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="StartingSpells">
        <xs:sequence>
            <xs:element name="Spell" type="Spell" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="LearnedSpells">
        <xs:sequence>
            <!-- todo: 14 is # of boxes on personal history sheet -->
            <xs:element name="Spell" type="Spell" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- todo: use sub group? permanent spells separate, since they have an 'isActivated' state (with activated time)
    Caster: artifact, spell-book (Treasure: eg - flying carpet), Character
        Character: dedicated chit, dedicated spell

        have a chit-id? infer id by position (1-12)?
    -->
    <xs:complexType name="Hireling">
        <xs:sequence>
            <xs:element name="ID" type="NativeId"/>
            <xs:element name="DayOfHire" type="GameDays" maxOccurs="unbounded"/>
            <!--
            <xs:element name="DayOfRehire" type="GameDays"/>
            -->
        </xs:sequence>
    </xs:complexType>
    <!-- minions? separate underlings and hired monsters? -->
    <xs:complexType name="Hirelings">
        <xs:sequence>
            <xs:element name="Hireling" type="Hireling" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ControlledMonster">
        <xs:sequence>
            <!-- todo: ref spell? -->
            <xs:element name="ID" type="MonsterId"/>
            <xs:element name="Bewitchment" type="BewitchmentId"/>
            <!-- 
            <xs:element name="SpellEffect" type="xs:string"/>
            <xs:element name="StartDay" type="xs:int"/>
            <xs:element name="EndDay" type="xs:int"/>
            -->
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ControlledMonsters">
        <xs:sequence>
            <xs:element name="ControlledMonster" type="ControlledMonster" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="VictoryCategory">
        <xs:sequence>
            <xs:element name="Category" type="NonEmptyString"/>
            <!-- multiplication factor -->
            <xs:element name="Factor" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="VictoryCategories">
        <xs:sequence>
            <xs:element name="VictoryCategory" type="VictoryCategory" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="VictoryRequirement">
        <xs:sequence>
            <!-- todo ref 
                Points: before multiplication
                -->
            <xs:element name="Category" type="NonEmptyString"/>
            <xs:element name="Points" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="VictoryRequirements">
        <xs:sequence>
            <!-- todo key ref -->
            <xs:element name="VictoryRequirement" type="VictoryRequirement" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!--
        todo: substitition group for activities?

    M <tile-id><clearing> <tile-id><clearing>
    H, F (who), S, P, EX, E, 
    qualifier: special advantage (bonus phase/reason)
    -->
    <xs:complexType name="RecordedActivity">
        <xs:sequence>
            <xs:element name="PhaseNumber" type="xs:positiveInteger"/>
            <!-- sources: Basic, Sunlight, horse, various bonuses, etc -->
            <xs:element name="PhaseSource" type="NonEmptyString"/>
            <!-- H, F, etc; sub group -->
            <xs:element name="PhaseActivity" type="NonEmptyString"/>
            <xs:element name="Notes" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="RecordedActivities">
        <xs:sequence>
            <xs:element name="RecordedActivity" type="RecordedActivity" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- todo: list all things which happened; strongly typed? -->
    <xs:complexType name="PC_TurnHistory">
        <xs:sequence>
            <xs:element name="Day" type="GameDays"/>
            <!-- time: evening, birdsong, etc; which player's turn (eg: discovered X on Y's turn) -->
            <xs:element name="TimeOfDay" type="NonEmptyString"/>
            <xs:element name="Turn" type="GameTurns"/>
            <xs:element name="Phase" type="GamePhases"/>
            <xs:element name="Notes" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PC_History">
        <xs:sequence>
            <xs:element name="PC_TurnHistory" type="PC_TurnHistory" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- todo: start date, end date -->
    <xs:complexType name="Missions">
        <xs:sequence>
            <xs:element name="Mission" type="Mission" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- single campaign -->
    <xs:complexType name="Campaigns">
        <xs:sequence>
            <xs:element name="Campaign" type="Campaign" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <!-- todo history; activities
      should activities go somewhere else?
    -->
    <xs:complexType name="PlayerCharacter">
        <xs:sequence>
            <!-- character-name is unique per game -->
            <xs:element name="PlayerName" type="PlayerName"/>
            <xs:element name="CharacterName" type="CharacterName"/>
            <xs:element name="CharacterClass" type="CharacterClass"/>
            <xs:element name="Bio" type="xs:string"/>
            <xs:element name="Notes" type="xs:string"/>
            <!-- starting info; optional (if just starting, this may not have been picked yet)
                VC's are also in this category
                equipment must include the source (or it can be inferred via the equipment-id)
            <xs:group ref="StartingEquipment" minOccurs="0" maxOccurs="unbounded"/>

            includes status
            <xs:element name="Chits" type="PC_Chits" minOccurs="0"/>
         -->
            <xs:element name="StartingLocation" type="Dwelling" minOccurs="0"/>
            <xs:element name="StartingSpells" type="StartingSpells"/>
            <xs:element name="VictoryRequirements" type="VictoryRequirements"/>
            <!-- current activities; older ones are moved  to TurnHistory -->
            <xs:element name="RecordedActivities" type="RecordedActivities"/>
            <xs:element name="Hidden" type="xs:boolean"/>
            <xs:element name="Curses" type="Curses"/>
            <xs:element name="Bewitchments" type="Bewitchments"/>
            <xs:element name="Discoveries" type="Discoveries"/>
            <xs:element name="Hirelings" type="Hirelings"/>
            <xs:element name="ControlledMonsters" type="ControlledMonsters"/>
            <!-- Gold, Spells aren't 'normal belonging' -->
            <!-- Spells: should this be LearnedSpells or KnownSpells? -->
            <!-- maybe CharacterSpells should have attributes/child elements
              to refer to bewitchments? should the association be bi-directional?
            -->
            <xs:element name="LearnedSpells" type="LearnedSpells"/>
            <xs:element name="Gold" type="GoldPrice"/>
            <xs:element name="Fame" type="FameType"/>
            <xs:element name="Notoriety" type="NotorietyType"/>
            <xs:element name="ActiveBelongings" type="ActiveBelongings"/>
            <xs:element name="InactiveBelongings" type="InactiveBelongings"/>
            <xs:element name="Missions" type="Missions"/>
            <xs:element name="Campaigns" type="Campaigns"/>
            <xs:element name="PC_History" type="PC_History"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="PlayerCharacters">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PlayerCharacter" type="PlayerCharacter" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/PlayerCharacters.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayerCharacters xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="PlayerCharacters.xsd">
    <PlayerCharacter>
        <PlayerName>Craigp</PlayerName>
        <CharacterName>Nadine</CharacterName>
        <CharacterClass>Amazon</CharacterClass>
        <Bio>amazons rule!!</Bio>
        <Notes>my notes</Notes>
        <StartingLocation>Inn</StartingLocation>
        <StartingSpells></StartingSpells>
        <VictoryRequirements></VictoryRequirements>
        <RecordedActivities>
            <RecordedActivity>
                <PhaseNumber>1</PhaseNumber>
                <PhaseSource>Basic</PhaseSource>
                <PhaseActivity>H</PhaseActivity>
                <Notes></Notes>
            </RecordedActivity>
        </RecordedActivities>
        <Hidden>false</Hidden>
        <Curses></Curses>
        <Bewitchments></Bewitchments>
        <Discoveries></Discoveries>
        <Hirelings></Hirelings>
        <ControlledMonsters></ControlledMonsters>
        <LearnedSpells></LearnedSpells>
        <Gold>10</Gold>
        <Fame>0</Fame>
        <Notoriety>0</Notoriety>
        <ActiveBelongings>
            <Pony>1</Pony>
        </ActiveBelongings>
        <InactiveBelongings></InactiveBelongings>
        <Missions></Missions>
        <Campaigns></Campaigns>
        <PC_History></PC_History>
    </PlayerCharacter>
</PlayerCharacters>
