=== BackupTheBerlios/magicrealmdev-svn/trunk/xmlData/Spells.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="MagicTypes.xsd"/>
    <xs:complexType name="SpellData">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Type" type="RitualMagic"/>
            <xs:element name="Color" type="ColorMagic"/>
            <xs:element name="Target" type="SpellTarget"/>
            <xs:element name="Duration" type="SpellDuration"/>
            <!-- todo: wtf is Source?? -->
            <xs:element name="Source" type="xs:string"/>
            <xs:element name="Description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="SpellList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Spell" type="SpellData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackupTheBerlios/magicrealmdev-svn/trunk/resources/xmlData/Spells.xml
<?xml version="1.0" encoding="utf-8"?>
<SpellList
      xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    
      xsi:noNamespaceSchemaLocation="Spells.xsd">

  <Spell>
    <Name>Exorcise</Name>
    <Type>I</Type>
    <Color>White</Color>
    <Target>the spellcaster's clearing</Target>
    <Duration>Instant</Duration>
    <Source>MR</Source>
    <Description> Every Demon and Imp in the clearing is killed. Every spell and Curse that is in effect in the clearing or that is being cast in the clearing this round is instantly broken. All &lt;i&gt;color&lt;/i&gt; chits in the clearing instantly fatigue. This spell is the strobgest of all, and it nullifies and breaks all other spells.</Description>
  </Spell>
  <Spell>
    <Name>Make Whole</Name>
    <Type>I</Type>
    <Color>White</Color>
    <Target>one character</Target>
    <Duration>Instant</Duration>
    <Source>MR</Source>
    <Description> This spell activates all of the target's fatigued and wounded action chits and repairs all of his damaged armor (including his inactive armor). It affects only those chits that are already inactive and only that armor that is already damaged - it does not affect fatigue, wounds and damage that are inflicted during the current round of combat. This spell's strength is equal to the POWER OF THE PIT results that affect action chits and armor (it does not conflict with the other POWER OF THE PIT results). &lt;i&gt;Special:&lt;/i&gt; This spell breaks the WITHER Curse on the target.</Description>
  </Spell>
  <Spell>
    <Name>Peace</Name>
    <Type>I</Type>
    <Color>White</Color>
    <Target>one character, native or monster</Target>
    <Duration>Combat</Duration>
    <Source>MR</Source>
    <Description> When this spell goes into effect, it is instantly broken if its target is currently the target of any other character or denizen. If he is not someone else's target, the spell goes into effect.&lt;p&gt;&lt;b&gt;1.&lt;/b&gt;If the target is a denizen, whether hire</Description>
  </Spell>
  <Spell>
    <Name>Small Blessing</Name>
    <Type>I</Type>
    <Color>White</Color>
    <Target>one character</Target>
    <Duration>Instant</Duration>
    <Source>MR</Source>
    <Description> The target character immediately rolls the dice and consults the WISHES table.</Description>
  </Spell>
  <Spell>
    <Name>Blend into Background</Name>
    <Type>II</Type>
    <Color>Grey</Color>
    <Target>one character, hired leader or controlled monster</Target>
    <Duration>Day</Duration>
    <Source>MR</Source>
    <Description> The target can record and do an extra HIDE activity during his turn.</Description>
  </Spell>
  <Spell>
    <Name>Fog</Name>
    <Type>II</Type>
    <Color>Grey</Color>
    <Target>the spellcaster's hex tile</Target>
    <Duration>Day</Duration>
    <Source>MR</Source>
    <Description> This spell prevents an individual who is doing the SEARCH activity from using the PEER table. The spell affects every character, hired leader and controlled monster who is in the target tile or who is trying to search a clearing In the target tile (he cannot PEER into the tile from a mountain in an adjacent tile). This spell affects only the SEARCH activity. It does not prevent an individual from using spells or Treasure cards to do the PEER activity in the tile.</Description>
  </Spell>
  <Spell>
    <Name>Prophecy</Name>
    <Type>II</Type>
    <Color>Purple</Color>
    <Target>one character</Target>
    <Duration>Day</Duration>
    <Source>MR</Source>
    <Description> The target character Ignores his recorded turn and chooses what to do on each phase of his turn as he does the phase. He gets the same number of phases and types of activities he is normally allowed, except that he can use an extra or enhanced activity caused by a belonging as soon as he activates that belonging, whether it was active during &lt;i&gt;Birdsong&lt;/i&gt; or not. Only one horse per day can provide him with extra phases - once he has used an extra phase caused by one horse, for the rest of that day he cannot use extra phases caused by other horses. If this spell is broken before he finishes his turn, he is instantly blocked. &lt;i&gt;Note:&lt;/i&gt; His hired leaders, controlled monsters and phantasms must still do the turns recorded for them.</Description>
  </Spell>
  <Spell>
    <Name>Stones Fly</Name>
    <Type>II</Type>
    <Color>Grey</Color>
    <Target>any number of characters, natives and/or monsters</Target>
    <Duration>Attack</Duration>
    <Source>MR</Source>
    <Description> This spell attacks each target like a missile weapon with a length of 15, and it inflicts Light damage with one sharpness star (see rule 42.4). &lt;i&gt;Special:&lt;/i&gt; This spell always makes at least four attacks. If the spellcaster specifies one target, all four attacks are made against that target. If he specifies two targets, two attacks are made against each target. If he specifies three targets, two attacks are made against the target where he put his ATTENTION chit, and one attack is made against each other target. If he specifies four or more targets, one attack is made against each target. The spellcaster rolls separately on the MISSILE TABLE for each hit.</Description>
  </Spell>
  <Spell>
    <Name>Talk to Wise Bird</Name>
    <Type>II</Type>
    <Color>Gold</Color>
    <Target>one character</Target>
    <Duration>Instant</Duration>
    <Source>MR</Source>
    <Description> The target character immediately does a remote PEER activity. He specifies any clearing on the map and uses the PEER table to search that clearing.</Description>
  </Spell>
  <Spell>
    <Name>Witch's Brew</Name>
    <Type>II</Type>
    <Color>Grey</Color>
    <Target>any of the spellcaster's type II and type VIII MAGIC chits that he chooses</Target>
    <Duration>Day</Duration>
    <Source>MR</Source>
    <Description> Each targeted type II chit is transformed into a type IV chit, and each targeted type VIII chit Is transformed into a type Ill chit. See rule 43.5.</Description>
  </Spell>
  <Spell>
    <Name>Elvin Grace</Name>
    <Type>III</Type>
    <Color>Gold</Color>
    <Target>one character, monster or native</Target>
    <Duration>Combat</Duration>
    <Source>MR</Source>
    <Description> If the target is a character, this spell alters the time numbers on all of his MOVE chits. The strength on each MOVE chit defines its time number: each Light chit has a time of 1, each Medium chit has a time of 2, each Heavy chit has a time of 3,</Description>
  </Spell>
  <Spell>
    <Name>Faerie Lights</Name>
    <Type>III</Type>
    <Color>Gold</Color>
    <Target>any of the spellcaster's type III and type VII MAGIC chits that he chooses</Target>
    <Duration>Day</Duration>
    <Source>MR</Source>
    <Description> Each targeted type Ill chit is transformed into a type II chit, and each targeted type VII chit is transformed into a type VI chit. See rule 43.5.</Description>
  </Spell>
  <Spell>
    <Name>Illusion</Name>
    <Type>III</Type>
    <Color>Gold</Color>
    <Target>one character or the spellcaster's hex tile</Target>
    <Duration>Permanent</Duration>
    <Source>MR</Source>
    <Description> Each affected individual adds one to his result whenever he uses any SEARCH table. If the target is a tile, the spell affects every character, hired leader, controlled monster or phantasm in that tile.</Description>
  </Spell>
  <Spell>
    <Name>Lost</Name>
    <Type>III</Type>
    <Color>Gold</Color>
    <Target>one character or the spellcaster's hex tile</Target>
    <Duration>Permanent</Duration>
    <Source>MR</Source>
    <Description> Each affected individual moves randomly whenever he uses the MOVE activity to leave a clearing: instead of moving to the clearing he recorded, he must use the LOST table to determine which adjacent clearing he moves to.&lt;p&gt;&lt;b&gt;1.&lt;/b&gt;This spell affects an individual only when he uses the MOVE activity to leave a clearing. It does not affect him when he runs out of a clearing or when he starts a move between clearings, and it does not affect him when he flies.&lt;p&gt;&lt;b&gt;2.&lt;/b&gt;If the target is a tile, the spell affects every character, hired leader, controlled monster or phantasm who starts a MOVE activity in any clearing on that tile. The spell does not affect MOVE activities that start in other tiles.</Description>
  </Spell>
  <Spell>
    <Name>Persuade</Name>
    <Type>III</Type>
    <Color>Gold</Color>
    <Target>one native group, or all of the Giants in the spellcaster's clearing, or all of the Ogres in his clearing</Target>
    <Duration>Day</Duration>
    <Source>MR</Source>
    <Description> The spellcaster pacifies the targets as explained in rule 45. To hire them, he uses the FRIENDLY column of the MEETING table. &lt;i&gt;Special:&lt;/i&gt; When this spell is cast by an Artifact or Spell Book, the character who holds the item is the one who has pacified the denizens. If no character holds the item, the spell is nullified.</Description>
  </Spell>
  <Spell>
    <Name>See Hidden Signs</Name>
    <Type>III</Type>
    <Color>Gold</Color>
    <Target>one character</Target>
    <Duration>Day</Duration>
    <Source>MR</Source>
    <Description> The target can record and do one extra SEARCH activity during his turn.</Description>
  </Spell>
  <Spell>
    <Name>Blazing Light</Name>
    <Type>IV</Type>
    <Color>Purple</Color>
    <Target>cave clearing</Target>
    <Duration>Day</Duration>
    <Source>MR</Source>
